"use client";

import React, { createContext, useState, useContext, useEffect } from 'react';

export type LanguageCode = 'en' | 'hi' | 'mr';

export const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // App & Govt branding
    app_title: 'Legal Metrology Compliance Platform',
    govt_title: 'Government of India • Ministry of Consumer Affairs',
    dept_consumer_affairs: 'Department of Consumer Affairs',
    packaged_commodities: 'Packaged Commodities',
    compliance_portal: 'Compliance Portal',
    dept_govt_india: 'Dept of Consumer Affairs • Govt of India',
    packaged_commodities_compliance_portal: 'Packaged Commodities Compliance Portal',
    officer_id: 'Officer ID',
    main_home_page: 'Main Home Page',
    go_to_home_page: 'Go to Home Page',
    go_to_home: 'Go to Home',

    // Navigation items
    dashboard: 'Dashboard',
    new_scan: 'New Scan',
    products: 'Products',
    inspections: 'Inspections',
    reports: 'Reports',
    ecommerce_check: 'E-Commerce Audit',
    risk_analytics: 'Risk Analytics',
    consumer_portal: 'Consumer Portal',
    admin_terminal: 'Admin Terminal',

    // Dashboard Header & Controls
    enforcement_dashboard: 'Enforcement Dashboard',
    rule_engine_live: 'PCR 2011 Rule Engine Live',
    dashboard_subtitle: 'Department of Consumer Affairs • Legal Metrology (Packaged Commodities) Rules Enforcement Portal',
    refresh_data: 'Refresh Data',
    new_inspection_scan: 'New Inspection Scan',
    retry: 'Retry',
    unable_connect_backend: 'Unable to connect to Legal Metrology backend service.',

    // Stats Cards
    total_inspections: 'Total Inspections',
    compliance_rate: 'Compliance Rate',
    active_violations: 'Active Violations',
    products_scanned: 'Products Cataloged',
    vs_past_30_days: 'vs past 30 days',

    // Charts & Trends
    compliance_progression_trend: 'Compliance Progression Trend',
    trend_subtitle: '12-Month field audit compliance score trajectory',
    avg: 'Avg',
    compliance_percent: 'Compliance %',
    no_monthly_trends: 'No monthly audit trends yet',
    conducted_inspections_hint: 'Conducted field inspections will plot compliance trajectory over time.',

    // Statutory Infractions
    statutory_infractions: 'Statutory Infractions',
    violations_logged_rule: 'Violations logged by Legal Metrology rule',
    no_active_violations: 'No active violations recorded',
    violations_appear_hint: 'Statutory infractions will appear here upon inspection evaluation.',

    // Category Verification
    category_verification: 'Category Verification',
    category_subtitle: 'Compliant vs violation audits per commodity sector',
    compliant: 'Compliant',
    violations: 'Violations',
    no_category_records: 'No category audit records',
    category_appear_hint: 'Audit counts per commodity category will be charted here.',

    // Recent Scans Table
    recent_inspections_log: 'Recent Inspections Log',
    recent_inspections_subtitle: 'Commodities evaluated under Section 6 declarations',
    view_full_history: 'View Full History',
    col_inspection_id: 'Inspection ID',
    col_product_name: 'Product Name',
    col_category: 'Category',
    col_date: 'Date',
    col_score: 'Score',
    col_status: 'Status',
    status_compliant: 'Compliant',
    status_non_compliant: 'Non-Compliant',
    no_inspections_yet: 'No inspection records yet. Perform an AI scan to log your first inspection.',

    // Offline / Network
    offline_mode: 'Offline Mode',
    offline_field_mode: 'Offline Field Mode',
    network_online: 'Network Online',
    pending_sync: 'Pending Sync',
    pending: 'Pending',
    sync_now: 'Sync Offline Data',
    sync_offline_queue: 'Sync Offline Queue',
    syncing_batch: 'Syncing Batch...',

    // Profile & Menu
    sign_out: 'Sign Out',
    on_duty: 'On Duty',
    citizen_user: 'Citizen User',
    super_admin: 'Super-Admin',
    view_officer_id: 'View Official Officer ID Card',
    consumer_complaints_verification: 'Consumer Complaints & Verification',
    my_inspection_logs: 'My Inspection Logs',
    admin_terminal_rules: 'Admin Terminal & Rules',
    sign_out_platform: 'Sign Out of Platform',

    // Official ID Card Modal
    lmd_govt_india: 'Legal Metrology Department • Govt. of India',
    posting_jurisdiction: 'Posting Circle / Jurisdiction',
    statutory_warrant: 'Statutory Warrant',
    hrms_code: 'Govt Employee / HRMS Code',
    official_phone: 'Official Phone (Field 2FA)',
    digital_signature_verified: 'Digital Signature Verified',
    valid_till: 'VALID TILL 2028',
    close_credential_card: 'Close Credential Card',

    // ECommerce Page Tabs
    select_online_marketplace_title: '2. Select Online Marketplace Listing',
    presets_catalog_tab: 'Presets Catalog',
    product_link_url_tab: 'Product Link / URL',
    select_catalog_hint: 'Select catalog listing or paste live product web URL for automated cross-validation:',
    target_marketplace_listing: 'Target Marketplace Listing',
    select_online_product: '-- Select Online Product Listing --',
    scrape_and_fetch: 'Scrape & Fetch',
    quick_test_scenarios: '⚡ Quick Test Scenarios (1-Click Fill):',
    test_1_full_match: '✓ Test 1: Full Match (Parle-G)',
    test_2_mrp_discrepancy: '⚠ Test 2: MRP Discrepancy (ABC Drink)',
    test_3_qty_mismatch: '⚠ Test 3: Qty Mismatch (ABC Biscuits)',
    test_6_low_confidence: '⚠ Test 6: Low Confidence (XYZ Shampoo)',

    // Analytics Page
    analytics_title: 'Risk Prioritization & Manufacturer Analytics',
    analytics_subtitle: 'Data-driven manufacturer risk intelligence under Section 36 to target repeat offenders & prioritize field enforcement audits.',
    schedule_priority_audit: 'Schedule Priority Audit',
    critical_risk: 'Critical Risk',
    immediate_seizure: 'Immediate Seizure / Court',
    high_risk: 'High Risk',
    repeat_offender_multiplier: 'Repeat Offender Multiplier',
    medium_risk: 'Medium Risk',
    scheduled_audit_watchlist: 'Scheduled Audit Watchlist',
    low_risk_compliant: 'Low Risk / Compliant',
    clean_statutory_standing: 'Clean Statutory Standing',
    search_manufacturer: 'Search manufacturer by name or brand...',
    sec_36_enforcement_index: 'Section 36 Enforcement & Repeat Offender Index',
    fine_tiers: 'Fine Tiers: ₹25k / ₹50k / ₹100k + Imprisonment',
    manufacturer_entity: 'MANUFACTURER ENTITY',
    risk_level_header: 'RISK LEVEL',
    inspections_header: 'INSPECTIONS',
    repeat_violations_header: 'REPEAT VIOLATIONS',
    sec_36_penalty_tier: 'SECTION 36 PENALTY TIER',
    recommended_action: 'RECOMMENDED ENFORCEMENT ACTION',
    action_header: 'ACTION',
    audit_commodity: 'Audit Commodity',

    // ECommerce Page
    ecommerce_portal_title: 'E-Commerce Enforcement Portal',
    ecommerce_engine_live: 'Cross-Validation Engine',
    ecommerce_subtitle: 'Compare physical pack declarations against marketplace listings',
    physical_package_ocr: '1. Physical Package OCR Declarations',
    ecommerce_source: '2. E-Commerce Marketplace Source',
    manual_mode: 'Manual Mode',
    scan_offline_pack: 'Scan Offline Pack',
    upload_image: 'Upload Image',
    physical_printed_mrp: 'Physical Printed MRP',
    on_pack_mrp_hint: 'On-pack physical statutory declaration',
    declared_net_qty: 'Declared Net Quantity on Pack',
    paste_ecommerce_url: 'Paste E-Commerce Product Page URL / Link',
    cross_ref_loading: 'Cross-Referencing Statutory Declarations...',
    run_validation_btn: 'Run Legal Metrology Cross-Validation',
    audit_status: 'Audit Status',
    recent_audits: 'Recent E-Commerce Cross-Validation Audits',
    marketplace: 'Marketplace',
    seller_entity: 'Seller Entity',
    listed_net_qty: 'Listed Net Quantity',
    listed_manufacturer: 'Listed Manufacturer',
    online_declared_mrp: 'Online Declared MRP',
    offered_selling_price: 'Offered Selling Price',

    // Products Page
    products_repo_title: 'Registered Commodities Repository',
    items_cataloged: 'Items Cataloged',
    products_repo_subtitle: 'Pre-registered packaged commodity standards database for automated discrepancy cross-verification',
    refresh_products: 'Refresh Products',
    register_commodity_btn: 'Register Commodity',
    failed_load_products: 'Failed to load products repository.',
    search_products_placeholder: 'Search by Product Name, Manufacturer, Barcode, or ID...',
    barcode_label: 'Barcode',
    standard_net_qty_label: 'Standard Net Qty',
    registered_mrp_label: 'Registered MRP',
    commodity_id_col: 'Commodity ID',
    product_name_col: 'Product Name',
    manufacturer_col: 'Manufacturer',
    category_col: 'Category',
    register_new_commodity_title: 'Register New Packaged Commodity',
    commodity_name_label: 'Commodity / Product Name',
    commodity_name_placeholder: 'e.g. Classic Salted Potato Chips 50g',
    mfg_name_address_label: 'Manufacturer Name & Address',
    mfg_name_address_placeholder: 'e.g. ABC Foods Pvt Ltd, Okhla Ind Area, Delhi',
    category_label: 'Category',
    ean13_barcode_label: 'EAN-13 Barcode',
    ean13_placeholder: 'e.g. 8901234567899',
    standard_metric_qty_label: 'Standard Metric Net Qty',
    standard_metric_qty_placeholder: 'e.g. 50g or 100ml',
    registered_mrp_rupees_label: 'Registered MRP (₹)',
    registered_mrp_rupees_placeholder: 'e.g. ₹20.00',
    save_commodity_btn: 'Save Commodity',
    saving_btn: 'Saving...',
    cancel_btn: 'Cancel',

    // Landing Page Modals
    report_violation_modal_title: 'Report a Packaging Violation',
    report_violation_modal_subtitle: 'Legal Metrology Act, 2009 (Sec 36)',
    product_name_brand_label: 'Product Name & Brand *',
    product_name_placeholder: 'e.g. Mineral Water Bottle 1L / Brand XYZ',
    retailer_platform_label: 'Retailer, Mall, Airport or E-Commerce Platform *',
    retailer_placeholder: 'e.g. Metro Station Kiosk, Blinkit, Supermarket',
    violation_type_label: 'Violation Type',
    violation_type_opt_1: 'Dual MRP / Overcharging (Rule 18)',
    violation_type_opt_2: 'Smudged / Altered MRP',
    violation_type_opt_3: 'Missing Net Quantity',
    violation_type_opt_4: 'Non-Standard Packaging Weight',
    violation_type_opt_5: 'Missing Manufacturer / Importer Address',
    violation_type_opt_6: 'No Consumer Care Contact Details',
    city_state_label: 'City / State',
    city_state_placeholder: 'e.g. New Delhi, MH',
    brief_desc_evidence_label: 'Brief Description & Evidence Summary',
    brief_desc_placeholder: 'Explain the violation, charged price vs printed MRP...',
    submitting_btn: 'Submitting...',
    submit_enforcement_btn: 'Submit to Enforcement Wing',
    alerts_circulars_title: 'Official Notifications & Advisories',
    circular_1_tag: 'CIRCULAR #2025/LM/09',
    circular_1_title: 'Advisory on Correct Net Quantity Declaration',
    circular_1_desc: 'State Enforcement Directorates are directed to conduct special drives verifying net quantity declarations on packaged food items and pulses.',
    circular_1_date: 'Published: Sep 5, 2025',
    circular_2_tag: 'AMENDMENT 2025',
    circular_2_title: 'Revised Guidelines for Multipack Commodities',
    circular_2_desc: 'Multipacks containing individual units intended for separate sale must declare the individual unit price alongside the total package MRP.',
    circular_2_date: 'Published: Aug 28, 2025',
    circular_3_tag: 'CAMPAIGN',
    circular_3_title: 'Nationwide Drive: Check Before You Buy',
    circular_3_desc: 'Public advisory encouraging consumers to verify the unit sale price (USP) and mandatory details before purchasing packaged goods.',
    circular_3_date: 'Published: Aug 12, 2025',

    // Consumer Page
    citizen_verification_title: 'Citizen Verification & Consumer Rights Portal',
    public_rights_section: 'Public Rights Section',
    consumer_empowerment_desc: 'Empowering consumers to verify statutory declarations, calculate nutritional index & report overcharging violations directly under Section 36.',
    lodge_complaint_btn: 'Lodge Overcharging Complaint',
    select_verified_commodity: 'Select Verified Commodity:',
    verified_packaged_commodity: 'VERIFIED PACKAGED COMMODITY',
    mfg_label: 'Mfg:',
    max_retail_price: 'Maximum Retail Price',
    net_metric_quantity: 'Net Metric Quantity',
    statutory_price_protection: 'Statutory Consumer Price Protection:',
    mrp_inclusive_taxes_desc: 'Maximum Retail Price inclusive of all taxes. Charging above printed MRP is an offence punishable under Section 36 of Legal Metrology Act.',
    verify_standard_units: 'Always verify that standard metric units (g/kg/ml) are printed without ambiguous qualifiers.',
    no_commodities_yet: 'No Commodities Cataloged Yet',
    commodities_will_appear_desc: 'Commodities registered by Legal Metrology Officers will appear here for statutory consumer verification. You can still report overcharging violations using the button above.',
    lodge_lm_complaint: 'Lodge Legal Metrology Complaint',
    complaint_registered_successfully: 'Complaint Registered Successfully',
    acknowledgement_id_label: 'Acknowledgement ID:',
    forwarded_inspector_desc: 'Forwarded to District Legal Metrology Inspector for immediate verification under Section 36.',
    retail_store_name_label: 'Retail Store / Vendor Name & Location',
    printed_pack_mrp_label: 'Printed Pack MRP',
    price_actually_charged_label: 'Price Actually Charged (₹)',
    complaint_nature_label: 'Complaint Nature',
    nature_overcharging: 'Overcharging above MRP (Dual Pricing)',
    nature_deficient_qty: 'Deficient Net Quantity / Short Measure',
    nature_missing_declarations: 'Missing Mandatory Declarations',
    nature_smudged_date: 'Smudged / Altered Date of Packing',
    complainant_contact_number: 'Complainant Contact Number',
    evidence_remarks: 'Evidence Remarks',
    submit_to_lmd_btn: 'Submit to Legal Metrology Dept',
    store_name_placeholder: 'e.g. Retail Mart, Market Road',
    charged_price_placeholder: 'e.g. 35.00',

    // Scan Page
    ai_inspection_subtitle: 'Upload product packaging to verify compliance with Legal Metrology Act, 2009',
    ai_inspection_title: 'AI Inspection',
    browse_photos: 'Browse Photos',
    camera_cancel: 'Cancel',
    camera_flip: 'Flip Camera',
    camera_snap: 'Snap Photo',
    capture_upload_desc: 'Drag and drop packaging image or snap a photo...',
    capture_upload_title: 'Upload Packaging Image',
    click_to_load_sample: 'Click to load sample',
    confidence_col: 'Confidence',
    confirm_col: 'Confirm',
    confirmed_label: 'Confirmed',
    create_certificate_desc: 'Generate an official compliance certificate',
    extracted_declarations_tab: 'Extracted Declarations',
    extracted_value_col: 'Extracted Value',
    fully_compliant: 'Fully Compliant',
    generate_official_certificate_btn: 'Generate Official Certificate',
    generate_report: 'Generate Report',
    generating_btn: 'Generating...',
    generating_report: 'Generating Report...',
    image_processed_desc: 'Image Processed',
    inspect_edit_confirm_desc: 'Review and confirm extracted details',
    inspected_sample_title: 'Inspected Sample',
    inspection_complete_title: 'Inspection Complete',
    lines_extracted: 'Lines Extracted',
    live_camera_title: 'Live Camera Viewfinder',
    live_field_camera: 'Live Field Camera',
    lm_eval_desc: 'Evaluation against rules',
    lm_eval_title: 'LM Rules Evaluation',
    lm_rules_desc: 'The Legal Metrology (Packaged Commodities) Rules, 2011 mandate...',
    lm_rules_tab: 'LM Rules Evaluation',
    location_label: 'Location',
    mandatory_decl_hitl_title: 'Mandatory Declarations (Human in the Loop)',
    mandatory_declaration_col: 'Mandatory Declaration',
    mandatory_declarations_check: 'Mandatory Declarations Check',
    manufacturer_label: 'Manufacturer',
    missing_not_detected_placeholder: 'Missing / Not Detected',
    new_packaging_scan: 'New Packaging Scan',
    non_compliant_violations: 'Non-Compliant Violations',
    ocr_accuracy_label: 'OCR Accuracy',
    ocr_evidence_tab: 'OCR Evidence',
    officer_observations_placeholder: 'Add any field observations...',
    officer_observations_title: 'Officer Observations',
    officer_override: 'Officer Override',
    officer_override_pass: 'Override Pass',
    passed_label: 'Passed',
    pdp_guide_desc: 'Align Declarations Here',
    pdp_guide_title: 'PRINCIPAL DISPLAY PANEL',
    print_certificate: 'Print Certificate',
    quick_catalog_testing: 'Quick Catalog Testing',
    raw_ocr_text_title: 'Raw OCR Text',
    re_evaluate_rules: 'Re-Evaluate Rules',
    readability_label: 'Readability',
    ready_for_ocr: 'Ready for OCR',
    revert_override: 'Revert Override',
    review_advised: 'Review Advised',
    rule_18_2_desc: 'No MRP Tampering/Overwriting',
    rule_6_1_a_desc: 'Manufacturer/Packer Name & Address',
    rule_6_1_b_desc: 'Generic/Commodity Name',
    rule_6_1_c_desc: 'Net Quantity (Metric System)',
    rule_6_1_d_desc: 'Month & Year of Mfg/Packing',
    rule_6_1_e_desc: 'Retail Sale Price (MRP)',
    rule_6_2_desc: 'Consumer Care Details',
    rule_7_font_label: 'Font Size Rule',
    run_ai_ocr: 'Run AI OCR',
    running_ocr_engine: 'Running OCR Engine...',
    save_offline_draft: 'Save Offline Draft',
    save_signed_evidence: 'Save Signed Evidence',
    scanning_extracting: 'Scanning & Extracting...',
    score_label: 'Score',
    sec_25_offline_desc: 'Inspections saved offline will securely synchronize...',
    sec_25_offline_title: 'Section 25 Offline Sync',
    selected_samples: 'Selected Samples',
    severity_label: 'Severity',
    violations_label: 'Violations',

    // Misc compliance rules
    dual_mrp_alert: 'Rule 18(2) Dual Pricing Detected',
    scan_btn: 'Upload or Capture Packaging',
    review_declarations: 'Human-in-the-Loop Review',
    statutory_rules: '15 Statutory Legal Metrology Rules',
    lodge_complaint: 'Lodge Overcharging Complaint (Sec 36)',

    // Scan Page

    // LANDING PAGE (Hero & Nav)
    ministry_consumer_affairs: 'Ministry of Consumer Affairs, Food & Public Distribution',
    govt_of_india: 'Government of India',
    portal_title: 'Packaged Commodities Compliance Portal',
    portal_tagline: 'Transparent Weights. Trusted Consumers. Stronger India.',
    nav_home: 'Home',
    nav_check_product: 'Check Product',
    nav_know_rules: 'Know the Rules',
    nav_consumer_awareness: 'Consumer Awareness',
    nav_report_violation: 'Report Violation',
    nav_dashboard: 'Dashboard',
    nav_resources: 'Resources',
    nav_about_us: 'About Us',
    search_placeholder: 'Search products, rules, etc.',
    right_info: 'Right Information',
    stronger_consumers: 'Stronger Consumers',
    ensuring_fair_trade: 'ENSURING FAIR TRADE',
    check_compliance_title: 'Check Compliance of Packaged Commodities',
    check_compliance_desc: 'Verify whether a packaged product complies with the Legal Metrology (Packaged Commodities) Rules, 2011.',
    btn_check_product: 'Check a Product',
    btn_learn_more: 'Learn More',
    badge_consumer_protection: 'Consumer Protection',
    badge_fair_measurement: 'Fair Measurement',
    badge_trusted_marketplace: 'Trusted Marketplace',
    card_check_product_desc: 'Scan or enter details to verify compliance',
    card_understand_rules: 'Understand the Rules',
    card_understand_rules_desc: 'Learn about Legal Metrology Rules, 2011',
    card_report_violation: 'Report a Violation',
    card_report_violation_desc: 'Help us ensure fair trade',
    card_consumer_awareness: 'Consumer Awareness',
    card_consumer_awareness_desc: 'Tips, guides and resources',
    card_compliance_dashboard: 'Compliance Dashboard',
    card_compliance_dashboard_desc: 'State-wise insights and reports',

    section_check_product: 'Check a Packaged Product',
    lm_rules_badge: 'LM Rules 2011',
    tab_scan_barcode: 'Scan Barcode',
    tab_enter_details: 'Enter Details',
    tab_upload_image: 'Upload Image',
    scan_barcode_desc: 'Scan the barcode on the package to get product details and verify compliance.',
    btn_start_camera: 'Start Camera Scanner',
    test_known_barcode_label: 'Or Test with Known Barcode:',
    verify_btn: 'Verify',
    checking_btn: 'Checking...',
    quick_demo_label: 'Quick Demo:',
    sample_violation_btn: 'Sample Violation',
    enter_details_manual_link: "Don't have a barcode? Enter details manually →",
    section_categories: 'Supported Product Categories',
    cat_food: 'Food & Beverages',
    cat_cosmetics: 'Personal Care & Cosmetics',
    cat_household: 'Household Products',
    cat_healthcare: 'Healthcare & OTC Products',
    cat_other: 'All other packaged commodities',
    mandatory_decl_req: 'Mandatory Declarations Required:',
    mandatory_decl_list: 'Name & address of manufacturer/packer, common or generic name, net quantity, month & year of manufacture/import, retail sale price (MRP), and consumer care details.',
    section_alerts: 'Latest Alerts & Updates',
    view_all_link: 'View All',
    alert1_title: 'Advisory on Correct Net Quantity Declaration',
    alert1_desc: 'Ensure net quantity is declared in prescribed units as per LM Rules, 2011.',
    alert2_title: 'Revised Guidelines for Multipack Commodities',
    alert2_desc: 'New guidelines issued for declaration on multipack packages.',
    alert3_title: 'Awareness Campaign: Check Before You Buy',
    alert3_desc: 'Join our campaign to promote informed and safe consumer choices.',

    rules_modal_title: 'Legal Metrology (Packaged Commodities) Rules, 2011',
    rules_modal_subtitle: 'Statutory Provisions & Standards',
    rule_6_title: 'Rule 6: Mandatory Declarations',
    rule_6_desc: 'Every package must bear the following clear, unsmudged declarations:',
    rule_6_l1: 'Name and complete address of the manufacturer, packer, or importer.',
    rule_6_l2: 'Common or generic name of the commodity contained in the package.',
    rule_6_l3: 'Net quantity in terms of standard unit of weight or measure (g, kg, ml, L, m).',
    rule_6_l4: 'Month and year in which the commodity is manufactured, packed or imported.',
    rule_6_l5: 'Retail sale price (MRP) in Indian currency, inclusive of all taxes.',
    rule_6_l6: 'Name, address, telephone number, and email of person or office for consumer complaints.',
    rule_18_title: 'Rule 18(2): Prohibition of Dual MRP',
    rule_18_desc: 'No manufacturer, packer, importer or seller shall alter, smudge, or paste another price over the retail sale price declared on the package. Charging above MRP or having two different MRPs for identical products at different venues (e.g. airports vs local markets) is an offence under Section 36 of the Act.',
    second_schedule_title: 'Second Schedule: Standard Package Sizes',
    second_schedule_desc: 'Specified commodities such as baby milk, biscuits, tea, salt, and edible oils must only be packed in prescribed standard quantities (e.g. 100g, 200g, 500g, 1kg) to prevent deceptive packaging.',
    close_guidelines_btn: 'Close Guidelines',

    awareness_modal_title: 'Jago Grahak Jago — Consumer Rights',
    awareness_modal_subtitle: 'Know What to Check Before You Pay',
    awareness_point1_title: 'Never Pay Above MRP:',
    awareness_point1_desc: "MRP is statutory and always includes all applicable taxes (GST). Extra 'cooling charges' or 'convenience fee' on packaged goods are illegal.",
    awareness_point2_title: 'Inspect Net Weight:',
    awareness_point2_desc: 'Ensure the package contains the exact declared weight and is not underweight. Use verified trade scales available at retail counters.',
    awareness_point3_title: 'Check Customer Care Details:',
    awareness_point3_desc: 'Every legal package must have an email, telephone, and postal address for grievances.',
    awareness_help_title: 'Need immediate assistance?',
    awareness_help_text1: 'Call National Consumer Helpline at',
    awareness_help_text2: "or SMS 'CONSUMER' to 8800001915.",
    understood_btn: 'Understood',

    // Dashboard Page
    products_cataloged: 'Products Cataloged',

    // Dashboard Layout

    // ECommerce Page Tabs

    // Analytics Page

    // ECommerce Page

    // Products Page

    // Landing Page Modals

    // Consumer Page

    // Scan Page
  },
  hi: {
    // App & Govt branding
    app_title: 'विधिक मापविज्ञान अनुपालन मंच',
    govt_title: 'भारत सरकार • उपभोक्ता मामले मंत्रालय',
    dept_consumer_affairs: 'उपभोक्ता मामले विभाग',
    packaged_commodities: 'पैकेज्ड वस्तुएं',
    compliance_portal: 'अनुपालन पोर्टल',
    dept_govt_india: 'उपभोक्ता मामले विभाग • भारत सरकार',
    packaged_commodities_compliance_portal: 'पैकेज्ड वस्तुएं अनुपालन पोर्टल',
    officer_id: 'अधिकारी पहचान पत्र',
    main_home_page: 'मुख्य होम पेज',
    go_to_home_page: 'मुख्य पृष्ठ पर जाएं',
    go_to_home: 'मुख्य पृष्ठ पर जाएं',

    // Navigation items
    dashboard: 'डैशबोर्ड',
    new_scan: 'नया स्कैन / निरीक्षण',
    products: 'उत्पाद सूची',
    inspections: 'निरीक्षण इतिहास',
    reports: 'प्रमाणपत्र एवं रिपोर्ट्स',
    ecommerce_check: 'ई-कॉमर्स जांच (दोहरा MRP)',
    risk_analytics: 'जोखिम विश्लेषण (धारा 36)',
    consumer_portal: 'उपभोक्ता मंच (जागो ग्राहक)',
    admin_terminal: 'व्यवस्थापक टर्मिनल (Admin)',

    // Dashboard Header & Controls
    enforcement_dashboard: 'प्रवर्तन डैशबोर्ड',
    rule_engine_live: 'पीसीआर 2011 नियम इंजन लाइव',
    dashboard_subtitle: 'उपभोक्ता मामले विभाग • विधिक मापविज्ञान (पैकेज्ड वस्तुएं) नियम प्रवर्तन पोर्टल',
    refresh_data: 'डेटा रिफ्रेश करें',
    new_inspection_scan: 'नया निरीक्षण स्कैन',
    retry: 'पुनः प्रयास करें',
    unable_connect_backend: 'विधिक मापविज्ञान बैकएंड सेवा से कनेक्ट करने में असमर्थ।',

    // Stats Cards
    total_inspections: 'कुल निरीक्षण',
    compliance_rate: 'अनुपालन दर',
    active_violations: 'सक्रिय उल्लंघन',
    products_scanned: 'सत्यापित उत्पाद',
    vs_past_30_days: 'पिछले 30 दिनों की तुलना में',

    // Charts & Trends
    compliance_progression_trend: 'अनुपालन प्रगति रुझान',
    trend_subtitle: '12-महीने का फील्ड ऑडिट अनुपालन स्कोर प्रक्षेपवक्र',
    avg: 'औसत',
    compliance_percent: 'अनुपालन %',
    no_monthly_trends: 'अभी तक कोई मासिक ऑडिट रुझान नहीं',
    conducted_inspections_hint: 'किए गए फील्ड निरीक्षण समय के साथ अनुपालन रुझान प्रदर्शित करेंगे।',

    // Statutory Infractions
    statutory_infractions: 'वैधानिक उल्लंघन',
    violations_logged_rule: 'विधिक मापविज्ञान नियम अनुसार दर्ज उल्लंघन',
    no_active_violations: 'कोई सक्रिय उल्लंघन दर्ज नहीं',
    violations_appear_hint: 'निरीक्षण मूल्यांकन के बाद वैधानिक उल्लंघन यहां दिखाई देंगे।',

    // Category Verification
    category_verification: 'श्रेणी सत्यापन',
    category_subtitle: 'वस्तु क्षेत्र अनुसार अनुपालन बनाम उल्लंघन ऑडिट',
    compliant: 'अनुपालक',
    violations: 'उल्लंघन',
    no_category_records: 'कोई श्रेणी ऑडिट रिकॉर्ड नहीं',
    category_appear_hint: 'वस्तु श्रेणी अनुसार ऑडिट संख्या यहां प्रदर्शित होगी।',

    // Recent Scans Table
    recent_inspections_log: 'हालिया निरीक्षण लॉग',
    recent_inspections_subtitle: 'धारा 6 घोषणाओं के तहत मूल्यांकित वस्तुएं',
    view_full_history: 'संपूर्ण इतिहास देखें',
    col_inspection_id: 'निरीक्षण आईडी',
    col_product_name: 'उत्पाद का नाम',
    col_category: 'श्रेणी',
    col_date: 'दिनांक',
    col_score: 'स्कोर',
    col_status: 'स्थिति',
    status_compliant: 'अनुपालक',
    status_non_compliant: 'गैर-अनुपालक',
    no_inspections_yet: 'अभी तक कोई निरीक्षण रिकॉर्ड नहीं है। पहला निरीक्षण दर्ज करने के लिए AI स्कैन करें।',

    // Offline / Network
    offline_mode: 'ऑफलाइन मोड',
    offline_field_mode: 'ऑफलाइन फील्ड मोड',
    network_online: 'नेटवर्क ऑनलाइन',
    pending_sync: 'सिंक लंबित',
    pending: 'लंबित',
    sync_now: 'ऑफलाइन डेटा सिंक करें',
    sync_offline_queue: 'ऑफलाइन कतार सिंक करें',
    syncing_batch: 'बैच सिंक हो रहा है...',

    // Profile & Menu
    sign_out: 'लॉग आउट',
    on_duty: 'कर्तव्यस्थ (On Duty)',
    citizen_user: 'नागरिक उपयोगकर्ता',
    super_admin: 'मुख्य प्रशासक',
    view_officer_id: 'अधिकारी पहचान पत्र देखें',
    consumer_complaints_verification: 'उपभोक्ता शिकायतें एवं सत्यापन',
    my_inspection_logs: 'मेरे निरीक्षण लॉग',
    admin_terminal_rules: 'व्यवस्थापक टर्मिनल एवं नियम',
    sign_out_platform: 'मंच से लॉग आउट करें',

    // Official ID Card Modal
    lmd_govt_india: 'विधिक मापविज्ञान विभाग • भारत सरकार',
    posting_jurisdiction: 'तैनाती क्षेत्र / क्षेत्राधिकार',
    statutory_warrant: 'वैधानिक वारंट',
    hrms_code: 'सरकारी कर्मचारी / HRMS कोड',
    official_phone: 'आधिकारिक फोन (फील्ड 2FA)',
    digital_signature_verified: 'डिजिटल हस्ताक्षर सत्यापित',
    valid_till: 'वैधता: 2028 तक',
    close_credential_card: 'पहचान पत्र बंद करें',

    // Misc compliance rules
    dual_mrp_alert: 'नियम 18(2) दोहरा एमआरपी उल्लंघन',
    scan_btn: 'पैकेजिंग फोटो कैप्चर या अपलोड करें',
    review_declarations: 'अधिकारी सत्यापन तालिका',
    statutory_rules: '15 विधिक मापविज्ञान नियम',
    lodge_complaint: 'अतिरिक्त वसूली की शिकायत दर्ज करें',

    // Scan Page
    live_camera_title: 'लाइव पैकेजिंग निरीक्षण कैमरा',
    camera_flip: 'फ्लिप',
    camera_cancel: 'रद्द करें',
    camera_snap: 'फोटो लें और उपयोग करें',
    pdp_guide_title: 'मुख्य प्रदर्शन पैनल (PDP) गाइड',
    pdp_guide_desc: 'एमआरपी, शुद्ध मात्रा, बैच और निर्माण तिथि को बॉक्स में रखें',
    ai_inspection_title: 'AI पैकेजिंग निरीक्षण और निष्कर्षण',
    ai_inspection_subtitle: 'स्वचालित ओसीआर निष्कर्षण और विधिक मापविज्ञान (पैकेज्ड वस्तुएं) नियम सत्यापन',
    new_packaging_scan: 'नया पैकेजिंग स्कैन',
    capture_upload_title: 'उत्पाद पैकेजिंग कैप्चर या अपलोड करें',
    capture_upload_desc: 'पैकेजिंग चित्र (आगे, पीछे, साइड पैनल) अपलोड करें या डिवाइस कैमरे से लाइव फोटो लें। एआई इंजन विधिक मापविज्ञान नियमों के तहत सभी अनिवार्य घोषणाओं को निकालता है।',
    browse_photos: 'पैकेजिंग तस्वीरें ब्राउज़ करें',
    live_field_camera: 'लाइव फील्ड कैमरा',
    quick_catalog_testing: 'त्वरित कैटलॉग बेंचमार्क परीक्षण:',
    click_to_load_sample: 'पैकेजिंग नमूना तुरंत लोड करने के लिए क्लिक करें',
    selected_samples: 'चयनित नमूने',
    ready_for_ocr: 'ओसीआर और नियम इंजन के लिए तैयार',
    save_offline_draft: 'ऑफलाइन ड्राफ्ट सहेजें',
    run_ai_ocr: 'एआई ओसीआर निष्कर्षण और नियम मूल्यांकन चलाएं',
    scanning_extracting: 'घोषणाएं स्कैन और निकाली जा रही हैं...',
    running_ocr_engine: 'ईज़ीओसीआर, कंट्रास्ट एन्हांसमेंट और विधिक मापविज्ञान नियम इंजन चल रहा है...',
    mandatory_declarations_check: 'अनिवार्य घोषणाएं जांच',
    lm_rules_desc: 'विधिक मापविज्ञान (पैकेज्ड वस्तुएं) नियम, 2011 के अनुसार, प्रत्येक खुदरा पैकेज पर प्रदर्शित होना चाहिए:',
    rule_6_1_a_desc: 'नियम 6(1)(a): पिन के साथ निर्माता का नाम और डाक पता',
    rule_6_1_b_desc: 'नियम 6(1)(b): जेनेरिक / सामान्य वस्तु का नाम',
    rule_6_1_c_desc: 'नियम 6(1)(c): मीट्रिक एसआई इकाइयों में शुद्ध मात्रा (नियम 12)',
    rule_6_1_e_desc: 'नियम 6(1)(e): रुपये (₹) प्रतीक और "सभी करों सहित" के साथ एमआरपी',
    rule_6_1_d_desc: 'नियम 6(1)(d): निर्माण/पैकिंग का माह और वर्ष',
    rule_6_2_desc: 'नियम 6(2): उपभोक्ता शिकायत संपर्क (फोन/ईमेल)',
    rule_18_2_desc: 'नियम 18(2): कोई दोहरा मूल्य निर्धारण या रीस्टिकरिंग नहीं',
    sec_25_offline_title: 'धारा 25 ऑफलाइन निरीक्षण',
    sec_25_offline_desc: 'क्षेत्रीय अधिकारी बिना इंटरनेट के ऑफलाइन बाजारों में पैकेजिंग फोटो ले सकते हैं। ड्राफ्ट स्थानीय रूप से कतारबद्ध होते हैं और कनेक्ट होने पर बैच मोड में सिंक्रनाइज़ होते हैं।',
    fully_compliant: 'पूरी तरह से अनुपालक',
    review_advised: 'समीक्षा की सलाह दी',
    non_compliant_violations: 'गैर-अनुपालक / उल्लंघन',
    score_label: 'स्कोर',
    manufacturer_label: 'निर्माता:',
    category_label: 'श्रेणी:',
    readability_label: 'पठनीयता',
    rule_7_font_label: 'नियम 7 फ़ॉन्ट',
    ocr_accuracy_label: 'ओसीआर सटीकता',
    inspection_complete_title: 'निरीक्षण पूर्ण — आधिकारिक रिपोर्ट तैयार करें',
    create_certificate_desc: 'विधिक मापविज्ञान अधिनियम 2009 की धारा 24 के तहत वैधानिक अनुपालन प्रमाणपत्र या जुर्माना नोटिस बनाएं',
    print_certificate: 'प्रमाणपत्र प्रिंट करें',
    generate_report: 'रिपोर्ट तैयार करें',
    generating_report: 'रिपोर्ट तैयार की जा रही है...',
    extracted_declarations_tab: 'निकाली गई घोषणाओं की समीक्षा',
    lm_rules_tab: 'विधिक मापविज्ञान नियम',
    ocr_evidence_tab: 'पैकेजिंग ओसीआर साक्ष्य',
    re_evaluate_rules: 'नियमों का पुनर्मूल्यांकन करें',
    inspected_sample_title: 'निरीक्षित पैकेजिंग नमूना',
    image_processed_desc: 'डेस्क्यूइंग और कंट्रास्ट वृद्धि के साथ संसाधित छवि',
    mandatory_decl_hitl_title: 'अनिवार्य घोषणाएं (ह्यूमन-इन-द-लूप)',
    inspect_edit_confirm_desc: 'कानूनी प्रवर्तन से पहले ओसीआर-निकाले गए मानों का निरीक्षण, संपादन या पुष्टि करें',
    confirmed_label: 'पुष्टि की गई',
    mandatory_declaration_col: 'अनिवार्य घोषणा',
    extracted_value_col: 'निकाला गया टेक्स्ट मान',
    confidence_col: 'सटीकता',
    confirm_col: 'पुष्टि करें',
    missing_not_detected_placeholder: 'गुम या पता नहीं चला (दर्ज करने के लिए क्लिक करें)',
    location_label: 'स्थान:',
    lm_eval_title: 'विधिक मापविज्ञान अनुपालन मूल्यांकन',
    lm_eval_desc: 'LM(PC) नियम 2011 और विधिक मापविज्ञान अधिनियम 2009 के तहत स्वचालित नियम सत्यापन',
    passed_label: 'उत्तीर्ण',
    officer_override_pass: 'अधिकारी ओवरराइड (उत्तीर्ण)',
    revert_override: 'ओवरराइड वापस लें',
    officer_override: 'अधिकारी ओवरराइड',
    severity_label: 'गंभीरता',
    officer_observations_title: 'अधिकारी टिप्पणियां और वैधानिक प्रवर्तन रिमार्क',
    officer_observations_placeholder: 'धारा 49 के तहत भौतिक नमूने, सील अखंडता, खुदरा स्टोर स्थान, या शमन सिफारिश के संबंध में आधिकारिक अवलोकन दर्ज करें...',
    save_signed_evidence: 'हस्ताक्षरित साक्ष्य सहेजें',
    generate_official_certificate_btn: 'आधिकारिक अनुपालन प्रमाणपत्र / नोटिस तैयार करें →',
    generating_btn: 'तैयार किया जा रहा है...',
    raw_ocr_text_title: 'ओसीआर इंजन द्वारा खोजा गया रॉ पैकेजिंग टेक्स्ट',
    lines_extracted: 'पंक्तियां निकाली गईं',

    // LANDING PAGE (Hero & Nav)
    ministry_consumer_affairs: 'उपभोक्ता मामले, खाद्य और सार्वजनिक वितरण मंत्रालय',
    govt_of_india: 'भारत सरकार',
    portal_title: 'पैकेज्ड कमोडिटीज अनुपालन पोर्टल',
    portal_tagline: 'पारदर्शी वजन। विश्वसनीय उपभोक्ता। मजबूत भारत।',
    nav_home: 'होम',
    nav_check_product: 'उत्पाद जांचें',
    nav_know_rules: 'नियम जानें',
    nav_consumer_awareness: 'उपभोक्ता जागरूकता',
    nav_report_violation: 'उल्लंघन दर्ज करें',
    nav_dashboard: 'डैशबोर्ड',
    nav_resources: 'संसाधन',
    nav_about_us: 'हमारे बारे में',
    search_placeholder: 'उत्पाद, नियम आदि खोजें',
    right_info: 'सही जानकारी',
    stronger_consumers: 'मजबूत उपभोक्ता',
    ensuring_fair_trade: 'निष्पक्ष व्यापार सुनिश्चित करना',
    check_compliance_title: 'पैकेज्ड कमोडिटीज का अनुपालन जांचें',
    check_compliance_desc: 'सत्यापित करें कि क्या कोई पैकेज्ड उत्पाद लीगल मेट्रोलॉजी (पैकेज्ड कमोडिटीज) नियम, 2011 का अनुपालन करता है।',
    btn_check_product: 'उत्पाद जांचें',
    btn_learn_more: 'और जानें',
    badge_consumer_protection: 'उपभोक्ता संरक्षण',
    badge_fair_measurement: 'उचित माप',
    badge_trusted_marketplace: 'विश्वसनीय बाज़ार',
    card_check_product_desc: 'अनुपालन सत्यापित करने के लिए विवरण स्कैन या दर्ज करें',
    card_understand_rules: 'नियम समझें',
    card_understand_rules_desc: 'लीगल मेट्रोलॉजी नियम, 2011 के बारे में जानें',
    card_report_violation: 'उल्लंघन दर्ज करें',
    card_report_violation_desc: 'निष्पक्ष व्यापार सुनिश्चित करने में हमारी मदद करें',
    card_consumer_awareness: 'उपभोक्ता जागरूकता',
    card_consumer_awareness_desc: 'युक्तियाँ, मार्गदर्शिकाएँ और संसाधन',
    card_compliance_dashboard: 'अनुपालन डैशबोर्ड',
    card_compliance_dashboard_desc: 'राज्यवार अंतर्दृष्टि और रिपोर्ट',

    section_check_product: 'पैक किए गए उत्पाद की जांच करें',
    lm_rules_badge: 'एलएम नियम 2011',
    tab_scan_barcode: 'बारकोड स्कैन करें',
    tab_enter_details: 'विवरण दर्ज करें',
    tab_upload_image: 'छवि अपलोड करें',
    scan_barcode_desc: 'उत्पाद विवरण प्राप्त करने और अनुपालन सत्यापित करने के लिए पैकेज पर बारकोड को स्कैन करें।',
    btn_start_camera: 'कैमरा स्कैनर प्रारंभ करें',
    test_known_barcode_label: 'या ज्ञात बारकोड के साथ परीक्षण करें:',
    verify_btn: 'सत्यापित करें',
    checking_btn: 'जांच हो रही है...',
    quick_demo_label: 'त्वरित डेमो:',
    sample_violation_btn: 'नमूना उल्लंघन',
    enter_details_manual_link: "बारकोड नहीं है? मैन्युअल रूप से विवरण दर्ज करें →",
    section_categories: 'समर्थित उत्पाद श्रेणियां',
    cat_food: 'खाद्य और पेय पदार्थ',
    cat_cosmetics: 'व्यक्तिगत देखभाल और सौंदर्य प्रसाधन',
    cat_household: 'घरेलू उत्पाद',
    cat_healthcare: 'स्वास्थ्य देखभाल और ओटीसी उत्पाद',
    cat_other: 'अन्य सभी पैक की गई वस्तुएं',
    mandatory_decl_req: 'अनिवार्य घोषणाएं आवश्यक:',
    mandatory_decl_list: 'निर्माता/पैकर का नाम और पता, सामान्य या जेनेरिक नाम, शुद्ध मात्रा, निर्माण/आयात का महीना और वर्ष, खुदरा बिक्री मूल्य (एमआरपी), और उपभोक्ता देखभाल विवरण।',
    section_alerts: 'नवीनतम अलर्ट और अपडेट',
    view_all_link: 'सभी देखें',
    alert1_title: 'सही शुद्ध मात्रा घोषणा पर सलाह',
    alert1_desc: 'सुनिश्चित करें कि शुद्ध मात्रा एलएम नियम, 2011 के अनुसार निर्धारित इकाइयों में घोषित की गई है।',
    alert2_title: 'मल्टीपैक वस्तुओं के लिए संशोधित दिशानिर्देश',
    alert2_desc: 'मल्टीपैक पैकेजों पर घोषणा के लिए नए दिशानिर्देश जारी किए गए हैं।',
    alert3_title: 'जागरूकता अभियान: खरीदने से पहले जांचें',
    alert3_desc: 'सूचित और सुरक्षित उपभोक्ता विकल्पों को बढ़ावा देने के लिए हमारे अभियान में शामिल हों।',

    rules_modal_title: 'विधिक मापविज्ञान (पैकेज में रखी वस्तुएं) नियम, 2011',
    rules_modal_subtitle: 'वैधानिक प्रावधान और मानक',
    rule_6_title: 'नियम 6: अनिवार्य घोषणाएं',
    rule_6_desc: 'प्रत्येक पैकेज पर निम्नलिखित स्पष्ट घोषणाएं होनी चाहिए:',
    rule_6_l1: 'निर्माता, पैकर या आयातक का नाम और पूरा पता।',
    rule_6_l2: 'पैकेज में मौजूद वस्तु का सामान्य या जेनेरिक नाम।',
    rule_6_l3: 'वजन या माप की मानक इकाई (ग्राम, किग्रा, मिली, लीटर, मीटर) के संदर्भ में शुद्ध मात्रा।',
    rule_6_l4: 'जिस महीने और वर्ष में वस्तु का निर्माण, पैकिंग या आयात किया गया है।',
    rule_6_l5: 'सभी करों सहित भारतीय मुद्रा में खुदरा बिक्री मूल्य (एमआरपी)।',
    rule_6_l6: 'उपभोक्ता शिकायतों के लिए व्यक्ति या कार्यालय का नाम, पता, टेलीफोन नंबर और ईमेल।',
    rule_18_title: 'नियम 18(2): दोहरे एमआरपी पर प्रतिबंध',
    rule_18_desc: 'कोई भी निर्माता, पैकर, आयातक या विक्रेता पैकेज पर घोषित खुदरा बिक्री मूल्य को नहीं बदलेगा, मिटाएगा या उस पर कोई अन्य कीमत नहीं चिपकाएगा। एमआरपी से अधिक शुल्क लेना या विभिन्न स्थानों (जैसे हवाई अड्डों बनाम स्थानीय बाजारों) पर समान उत्पादों के लिए दो अलग-अलग एमआरपी रखना अधिनियम की धारा 36 के तहत अपराध है।',
    second_schedule_title: 'दूसरी अनुसूची: मानक पैकेज आकार',
    second_schedule_desc: 'भ्रामक पैकेजिंग को रोकने के लिए शिशु दुग्ध, बिस्कुट, चाय, नमक और खाद्य तेल जैसी निर्दिष्ट वस्तुओं को केवल निर्धारित मानक मात्राओं (जैसे 100 ग्राम, 200 ग्राम, 500 ग्राम, 1 किग्रा) में ही पैक किया जाना चाहिए।',
    close_guidelines_btn: 'दिशानिर्देश बंद करें',

    awareness_modal_title: 'जागो ग्राहक जागो — उपभोक्ता अधिकार',
    awareness_modal_subtitle: 'जानें कि भुगतान करने से पहले क्या जांचना चाहिए',
    awareness_point1_title: 'कभी भी एमआरपी से अधिक भुगतान न करें:',
    awareness_point1_desc: "एमआरपी वैधानिक है और इसमें हमेशा सभी लागू कर (जीएसटी) शामिल होते हैं। पैक किए गए सामानों पर अतिरिक्त 'कूलिंग चार्ज' या 'सुविधा शुल्क' अवैध हैं।",
    awareness_point2_title: 'शुद्ध वजन का निरीक्षण करें:',
    awareness_point2_desc: 'सुनिश्चित करें कि पैकेज में सटीक घोषित वजन है और वजन कम नहीं है। खुदरा काउंटरों पर उपलब्ध सत्यापित व्यापार तराजू का उपयोग करें।',
    awareness_point3_title: 'उपभोक्ता देखभाल विवरण जांचें:',
    awareness_point3_desc: 'प्रत्येक कानूनी पैकेज में शिकायतों के लिए एक ईमेल, टेलीफोन और डाक पता होना चाहिए।',
    awareness_help_title: 'तत्काल सहायता चाहिए?',
    awareness_help_text1: 'राष्ट्रीय उपभोक्ता हेल्पलाइन को',
    awareness_help_text2: "पर कॉल करें या 8800001915 पर 'CONSUMER' एसएमएस करें।",
    understood_btn: 'समझ गया',

    // Dashboard Page
    products_cataloged: 'सूचीबद्ध उत्पाद',

    // Dashboard Layout

    // ECommerce Page Tabs
    select_online_marketplace_title: '2. ऑनलाइन बाज़ार लिस्टिंग का चयन करें',
    presets_catalog_tab: 'प्रीसेट कैटलॉग',
    product_link_url_tab: 'उत्पाद लिंक / URL',
    select_catalog_hint: 'स्वचालित क्रॉस-सत्यापन के लिए कैटलॉग लिस्टिंग चुनें या लाइव उत्पाद वेब URL पेस्ट करें:',
    target_marketplace_listing: 'लक्षित बाज़ार लिस्टिंग',
    select_online_product: '-- ऑनलाइन उत्पाद लिस्टिंग चुनें --',
    scrape_and_fetch: 'डेटा निकालें (स्क्रैप और फेच)',
    quick_test_scenarios: '⚡ त्वरित परीक्षण परिदृश्य (1-क्लिक भरण):',
    test_1_full_match: '✓ टेस्ट 1: पूर्ण मिलान (Parle-G)',
    test_2_mrp_discrepancy: '⚠ टेस्ट 2: एमआरपी विसंगति (ABC Drink)',
    test_3_qty_mismatch: '⚠ टेस्ट 3: मात्रा विसंगति (ABC Biscuits)',
    test_6_low_confidence: '⚠ टेस्ट 6: कम आत्मविश्वास (XYZ Shampoo)',

    // Analytics Page
    analytics_title: 'जोखिम प्राथमिकता और निर्माता विश्लेषण',
    analytics_subtitle: 'धारा 36 के तहत डेटा-संचालित निर्माता जोखिम बुद्धिमत्ता, बार-बार अपराध करने वालों को लक्षित करने और क्षेत्र प्रवर्तन ऑडिट को प्राथमिकता देने के लिए।',
    schedule_priority_audit: 'प्राथमिकता ऑडिट शेड्यूल करें',
    critical_risk: 'अत्यधिक जोखिम',
    immediate_seizure: 'तत्काल जब्ती / न्यायालय',
    high_risk: 'उच्च जोखिम',
    repeat_offender_multiplier: 'बार-बार अपराधी गुणक',
    medium_risk: 'मध्यम जोखिम',
    scheduled_audit_watchlist: 'निर्धारित ऑडिट वॉचलिस्ट',
    low_risk_compliant: 'कम जोखिम / अनुपालक',
    clean_statutory_standing: 'स्वच्छ वैधानिक स्थिति',
    search_manufacturer: 'नाम या ब्रांड द्वारा निर्माता खोजें...',
    sec_36_enforcement_index: 'धारा 36 प्रवर्तन और बार-बार अपराधी सूचकांक',
    fine_tiers: 'जुर्माना स्तर: ₹25k / ₹50k / ₹100k + कारावास',
    manufacturer_entity: 'निर्माता इकाई',
    risk_level_header: 'जोखिम स्तर',
    inspections_header: 'निरीक्षण',
    repeat_violations_header: 'बार-बार उल्लंघन',
    sec_36_penalty_tier: 'धारा 36 दंड स्तर',
    recommended_action: 'अनुशंसित प्रवर्तन कार्रवाई',
    action_header: 'कार्रवाई',
    audit_commodity: 'वस्तु ऑडिट करें',

    // ECommerce Page
    ecommerce_portal_title: 'ई-कॉमर्स प्रवर्तन पोर्टल',
    ecommerce_engine_live: 'क्रॉस-सत्यापन इंजन',
    ecommerce_subtitle: 'बाज़ार लिस्टिंग के विरुद्ध भौतिक पैक घोषणाओं की तुलना करें',
    physical_package_ocr: '1. भौतिक पैकेज ओसीआर घोषणाएं',
    ecommerce_source: '2. ई-कॉमर्स बाज़ार स्रोत',
    manual_mode: 'मैनुअल मोड',
    scan_offline_pack: 'ऑफ़लाइन पैक स्कैन करें',
    upload_image: 'छवि अपलोड करें',
    physical_printed_mrp: 'भौतिक मुद्रित एमआरपी',
    on_pack_mrp_hint: 'पैक पर भौतिक वैधानिक घोषणा',
    declared_net_qty: 'पैक पर घोषित शुद्ध मात्रा',
    paste_ecommerce_url: 'ई-कॉमर्स उत्पाद पृष्ठ यूआरएल / लिंक पेस्ट करें',
    cross_ref_loading: 'वैधानिक घोषणाओं का मिलान किया जा रहा है...',
    run_validation_btn: 'विधिक मापविज्ञान क्रॉस-सत्यापन चलाएं',
    audit_status: 'ऑडिट स्थिति',
    recent_audits: 'हालिया ई-कॉमर्स क्रॉस-सत्यापन ऑडिट',
    marketplace: 'बाज़ार (मार्केटप्लेस)',
    seller_entity: 'विक्रेता इकाई',
    listed_net_qty: 'सूचीबद्ध शुद्ध मात्रा',
    listed_manufacturer: 'सूचीबद्ध निर्माता',
    online_declared_mrp: 'ऑनलाइन घोषित एमआरपी',
    offered_selling_price: 'प्रस्तावित बिक्री मूल्य',

    // Products Page
    products_repo_title: 'पंजीकृत कमोडिटी भंडार',
    items_cataloged: 'कैटलॉग किए गए आइटम',
    products_repo_subtitle: 'स्वचालित विसंगति क्रॉस-सत्यापन के लिए पूर्व-पंजीकृत पैक की गई वस्तु मानक डेटाबेस',
    refresh_products: 'उत्पाद रीफ्रेश करें',
    register_commodity_btn: 'कमोडिटी रजिस्टर करें',
    failed_load_products: 'उत्पाद भंडार लोड करने में विफल।',
    search_products_placeholder: 'उत्पाद का नाम, निर्माता, बारकोड या आईडी से खोजें...',
    barcode_label: 'बारकोड',
    standard_net_qty_label: 'मानक शुद्ध मात्रा',
    registered_mrp_label: 'पंजीकृत एमआरपी',
    commodity_id_col: 'कमोडिटी आईडी',
    product_name_col: 'उत्पाद का नाम',
    manufacturer_col: 'निर्माता',
    category_col: 'श्रेणी',
    register_new_commodity_title: 'नई पैक की गई कमोडिटी पंजीकृत करें',
    commodity_name_label: 'कमोडिटी / उत्पाद का नाम',
    commodity_name_placeholder: 'उदा. क्लासिक नमकीन आलू चिप्स 50 ग्राम',
    mfg_name_address_label: 'निर्माता का नाम और पता',
    mfg_name_address_placeholder: 'उदा. एबीसी फूड्स प्राइवेट लिमिटेड, ओखला औद्योगिक क्षेत्र, दिल्ली',
    ean13_barcode_label: 'EAN-13 बारकोड',
    ean13_placeholder: 'उदा. 8901234567899',
    standard_metric_qty_label: 'मानक मीट्रिक शुद्ध मात्रा',
    standard_metric_qty_placeholder: 'उदा. 50 ग्राम या 100 मिली',
    registered_mrp_rupees_label: 'पंजीकृत एमआरपी (₹)',
    registered_mrp_rupees_placeholder: 'उदा. ₹20.00',
    save_commodity_btn: 'कमोडिटी सहेजें',
    saving_btn: 'सहेजा जा रहा है...',
    cancel_btn: 'रद्द करें',

    // Landing Page Modals
    report_violation_modal_title: 'पैकेजिंग उल्लंघन की रिपोर्ट करें',
    report_violation_modal_subtitle: 'विधिक मापविज्ञान अधिनियम, 2009 (धारा 36)',
    product_name_brand_label: 'उत्पाद का नाम और ब्रांड *',
    product_name_placeholder: 'उदा. मिनरल वाटर की बोतल 1L / ब्रांड XYZ',
    retailer_platform_label: 'खुदरा विक्रेता, मॉल, हवाई अड्डा या ई-कॉमर्स प्लेटफॉर्म *',
    retailer_placeholder: 'उदा. मेट्रो स्टेशन कियोस्क, ब्लिंकिट, सुपरमार्केट',
    violation_type_label: 'उल्लंघन का प्रकार',
    violation_type_opt_1: 'दोहरा एमआरपी / अधिक मूल्य (नियम 18)',
    violation_type_opt_2: 'धुंधला / बदला हुआ एमआरपी',
    violation_type_opt_3: 'गायब शुद्ध मात्रा',
    violation_type_opt_4: 'गैर-मानक पैकेजिंग वजन',
    violation_type_opt_5: 'गायब निर्माता / आयातक का पता',
    violation_type_opt_6: 'कोई उपभोक्ता देखभाल संपर्क विवरण नहीं',
    city_state_label: 'शहर / राज्य',
    city_state_placeholder: 'उदा. नई दिल्ली, एमएच',
    brief_desc_evidence_label: 'संक्षिप्त विवरण और साक्ष्य सारांश',
    brief_desc_placeholder: 'उल्लंघन, लिए गए मूल्य बनाम मुद्रित एमआरपी की व्याख्या करें...',
    submitting_btn: 'जमा किया जा रहा है...',
    submit_enforcement_btn: 'प्रवर्तन विंग को जमा करें',
    alerts_circulars_title: 'आधिकारिक सूचनाएं और सलाह',
    circular_1_tag: 'परिपत्र #2025/LM/09',
    circular_1_title: 'सही शुद्ध मात्रा घोषणा पर सलाह',
    circular_1_desc: 'राज्य प्रवर्तन निदेशालयों को डिब्बाबंद खाद्य पदार्थों और दालों पर शुद्ध मात्रा की घोषणाओं को सत्यापित करने के लिए विशेष अभियान चलाने का निर्देश दिया गया है।',
    circular_1_date: 'प्रकाशित: 5 सितंबर, 2025',
    circular_2_tag: 'संशोधन 2025',
    circular_2_title: 'मल्टीपैक कमोडिटीज़ के लिए संशोधित दिशानिर्देश',
    circular_2_desc: 'अलग से बिक्री के लिए मल्टीपैक को कुल पैकेज एमआरपी के साथ-साथ व्यक्तिगत इकाई मूल्य की घोषणा करनी चाहिए।',
    circular_2_date: 'प्रकाशित: 28 अगस्त, 2025',
    circular_3_tag: 'अभियान',
    circular_3_title: 'राष्ट्रव्यापी अभियान: खरीदने से पहले जांचें',
    circular_3_desc: 'डिब्बाबंद सामान खरीदने से पहले उपभोक्ताओं को इकाई बिक्री मूल्य (USP) और अनिवार्य विवरण सत्यापित करने के लिए प्रोत्साहित करने वाली सार्वजनिक सलाह।',
    circular_3_date: 'प्रकाशित: 12 अगस्त, 2025',

    // Consumer Page
    citizen_verification_title: 'नागरिक सत्यापन और उपभोक्ता अधिकार पोर्टल',
    public_rights_section: 'सार्वजनिक अधिकार अनुभाग',
    consumer_empowerment_desc: 'उपभोक्ताओं को वैधानिक घोषणाओं को सत्यापित करने, पोषण सूचकांक की गणना करने और सीधे धारा 36 के तहत अधिक शुल्क लेने के उल्लंघनों की रिपोर्ट करने के लिए सशक्त बनाना।',
    lodge_complaint_btn: 'अधिक मूल्य लेने की शिकायत दर्ज करें',
    select_verified_commodity: 'सत्यापित कमोडिटी चुनें:',
    verified_packaged_commodity: 'सत्यापित पैक की गई कमोडिटी',
    mfg_label: 'निर्माता:',
    max_retail_price: 'अधिकतम खुदरा मूल्य',
    net_metric_quantity: 'शुद्ध मीट्रिक मात्रा',
    statutory_price_protection: 'वैधानिक उपभोक्ता मूल्य संरक्षण:',
    mrp_inclusive_taxes_desc: 'सभी करों सहित अधिकतम खुदरा मूल्य। मुद्रित एमआरपी से अधिक शुल्क लेना विधिक मापविज्ञान अधिनियम की धारा 36 के तहत दंडनीय अपराध है।',
    verify_standard_units: 'हमेशा सत्यापित करें कि मानक मीट्रिक इकाइयाँ (g/kg/ml) बिना किसी अस्पष्ट क्वालिफायर के मुद्रित हैं।',
    no_commodities_yet: 'अभी तक कोई कमोडिटी सूचीबद्ध नहीं है',
    commodities_will_appear_desc: 'विधिक मापविज्ञान अधिकारियों द्वारा पंजीकृत कमोडिटी उपभोक्ता सत्यापन के लिए यहां दिखाई देंगी। आप अभी भी ऊपर दिए गए बटन का उपयोग करके अधिक मूल्य लेने की रिपोर्ट कर सकते हैं।',
    lodge_lm_complaint: 'विधिक मापविज्ञान शिकायत दर्ज करें',
    complaint_registered_successfully: 'शिकायत सफलतापूर्वक पंजीकृत हुई',
    acknowledgement_id_label: 'पावती आईडी:',
    forwarded_inspector_desc: 'धारा 36 के तहत तत्काल सत्यापन के लिए जिला विधिक मापविज्ञान निरीक्षक को भेज दिया गया।',
    retail_store_name_label: 'खुदरा स्टोर / विक्रेता का नाम और स्थान',
    printed_pack_mrp_label: 'मुद्रित पैक एमआरपी',
    price_actually_charged_label: 'वास्तव में लिया गया मूल्य (₹)',
    complaint_nature_label: 'शिकायत की प्रकृति',
    nature_overcharging: 'एमआरपी से अधिक शुल्क (दोहरा मूल्य निर्धारण)',
    nature_deficient_qty: 'कम शुद्ध मात्रा / कम माप',
    nature_missing_declarations: 'अनिवार्य घोषणाएं गायब',
    nature_smudged_date: 'पैकिंग की धुंधली / बदली हुई तारीख',
    complainant_contact_number: 'शिकायतकर्ता संपर्क नंबर',
    evidence_remarks: 'साक्ष्य टिप्पणियां',
    submit_to_lmd_btn: 'विधिक मापविज्ञान विभाग को जमा करें',
    store_name_placeholder: 'उदा. रिटेल मार्ट, मार्केट रोड',
    charged_price_placeholder: 'उदा. 35.00',

    // Scan Page
    violations_label: 'उल्लंघन'
  },
  mr: {
    // App & Govt branding
    app_title: 'वैधानिक मापनशास्त्र अनुपालन मंच',
    govt_title: 'भारत सरकार • ग्राहक व्यवहार मंत्रालय',
    dept_consumer_affairs: 'ग्राहक व्यवहार विभाग',
    packaged_commodities: 'पॅकबंद वस्तू',
    compliance_portal: 'अनुपालन पोर्टल',
    dept_govt_india: 'ग्राहक व्यवहार विभाग • भारत सरकार',
    packaged_commodities_compliance_portal: 'पॅकबंद वस्तू अनुपालन पोर्टल',
    officer_id: 'अधिकारी ओळखपत्र',
    main_home_page: 'मुख्य होम पेज',
    go_to_home_page: 'मुख्य पृष्ठावर जा',
    go_to_home: 'मुख्य पृष्ठावर जा',

    // Navigation items
    dashboard: 'डॅशबोर्ड',
    new_scan: 'नवीन तपासणी स्कॅन',
    products: 'उत्पादन भांडार',
    inspections: 'तपासणी नोंदी',
    reports: 'अहवाल व प्रमाणपत्रे',
    ecommerce_check: 'ई-कॉमर्स तपासणी (दुहेरी MRP)',
    risk_analytics: 'धोका विश्लेषण (कलम 36)',
    consumer_portal: 'ग्राहक संरक्षण मंच',
    admin_terminal: 'प्रशासक नियंत्रण (Admin)',

    // Dashboard Header & Controls
    enforcement_dashboard: 'अंमलबजावणी डॅशबोर्ड',
    rule_engine_live: 'पीसीआर 2011 नियम इंजिन थेट सक्रिय',
    dashboard_subtitle: 'ग्राहक व्यवहार विभाग • वैधानिक मापनशास्त्र (पॅकबंद वस्तू) नियम अंमलबजावणी पोर्टल',
    refresh_data: 'डेटा रीफ्रेश करा',
    new_inspection_scan: 'नवीन तपासणी स्कॅन',
    retry: 'पुन्हा प्रयत्न करा',
    unable_connect_backend: 'वैधानिक मापनशास्त्र बॅकएंड सेवेशी जोडणी अशक्य.',

    // Stats Cards
    total_inspections: 'एकूण तपासण्या',
    compliance_rate: 'अनुपालन दर',
    active_violations: 'सक्रिय उल्लंघने',
    products_scanned: 'नोंदणीकृत उत्पादने',
    vs_past_30_days: 'मागील 30 दिवसांच्या तुलनेत',

    // Charts & Trends
    compliance_progression_trend: 'अनुपालन प्रगती कल',
    trend_subtitle: '12-महिन्यांचा क्षेत्रीय तपासणी अनुपालन स्कोअर आलेख',
    avg: 'सरासरी',
    compliance_percent: 'अनुपालन %',
    no_monthly_trends: 'अद्याप कोणताही मासिक तपासणी कल नाही',
    conducted_inspections_hint: 'केलेल्या प्रत्यक्ष तपासण्यांनुसार कालानुरूप अनुपालन आलेख तयार होईल.',

    // Statutory Infractions
    statutory_infractions: 'वैधानिक उल्लंघने',
    violations_logged_rule: 'वैधानिक मापनशास्त्र नियमांनुसार नोंदवलेली उल्लंघने',
    no_active_violations: 'कोणतेही सक्रिय उल्लंघन नोंदवलेले नाही',
    violations_appear_hint: 'तपासणी मूल्यमापनानंतर वैधानिक उल्लंघने येथे दिसतील.',

    // Category Verification
    category_verification: 'प्रवर्ग पडताळणी',
    category_subtitle: 'वस्तू क्षेत्रानुसार अनुपालन विरुद्ध उल्लंघन तपासणी',
    compliant: 'अनुपालित',
    violations: 'उल्लंघने',
    no_category_records: 'कोणतीही प्रवर्ग तपासणी नोंद नाही',
    category_appear_hint: 'वस्तूच्या वर्गवारीनुसार तपासणी संख्या येथे आलेख स्वरूपात दिसेल.',

    // Recent Scans Table
    recent_inspections_log: 'अलीकडील तपासणी नोंदी',
    recent_inspections_subtitle: 'कलम 6 च्या घोषणांनुसार मूल्यमापन केलेल्या वस्तू',
    view_full_history: 'संपूर्ण इतिहास पहा',
    col_inspection_id: 'तपासणी आयडी',
    col_product_name: 'उत्पादनाचे नाव',
    col_category: 'प्रवर्ग',
    col_date: 'दिनांक',
    col_score: 'गुण / स्कोअर',
    col_status: 'स्थिती',
    status_compliant: 'अनुपालित',
    status_non_compliant: 'गैर-अनुपालित',
    no_inspections_yet: 'अद्याप कोणतीही तपासणी नोंद नाही. पहिली तपासणी नोंदवण्यासाठी AI स्कॅन करा.',

    // Offline / Network
    offline_mode: 'ऑफलाइन मोड',
    offline_field_mode: 'ऑफलाइन फील्ड मोड',
    network_online: 'नेटवर्क सुरू आहे',
    pending_sync: 'सिंक बाकी',
    pending: 'प्रलंबित',
    sync_now: 'डेटा सिंक करा',
    sync_offline_queue: 'ऑफलाइन रांग सिंक करा',
    syncing_batch: 'बॅच सिंक होत आहे...',

    // Profile & Menu
    sign_out: 'बाहेर पडा',
    on_duty: 'कर्तव्यावर (On Duty)',
    citizen_user: 'नागरिक वापरकर्ता',
    super_admin: 'सुपर-अ‍ॅडमिन',
    view_officer_id: 'अधिकृत अधिकारी ओळखपत्र पहा',
    consumer_complaints_verification: 'ग्राहक तक्रारी व पडताळणी',
    my_inspection_logs: 'माझ्या तपासणी नोंदी',
    admin_terminal_rules: 'प्रशासक टर्मिनल व नियम',
    sign_out_platform: 'मंचावरून बाहेर पडा',

    // Official ID Card Modal
    lmd_govt_india: 'वैधानिक मापनशास्त्र विभाग • भारत सरकार',
    posting_jurisdiction: 'नियुक्ती विभाग / कार्यक्षेत्र',
    statutory_warrant: 'वैधानिक अधिकारपत्र',
    hrms_code: 'शासकीय कर्मचारी / HRMS कोड',
    official_phone: 'अधिकृत फोन (फील्ड 2FA)',
    digital_signature_verified: 'डिजिटल स्वाक्षरी प्रमाणित',
    valid_till: 'वैधता: 2028 पर्यंत',
    close_credential_card: 'ओळखपत्र बंद करा',

    // Misc compliance rules
    dual_mrp_alert: 'नियम 18(2) दुहेरी एमआरपी उल्लंघन',
    scan_btn: 'पॅकेजिंग फोटो काढा किंवा अपलोड करा',
    review_declarations: 'अधिकारी पडताळणी तक्ता',
    statutory_rules: '15 वैधानिक नियम तपासणी',
    lodge_complaint: 'जास्त दराची तक्रार नोंदवा',

    // Scan Page
    live_camera_title: 'थेट पॅकेजिंग तपासणी कॅमेरा',
    camera_flip: 'फ्लिप करा',
    camera_cancel: 'रद्द करा',
    camera_snap: 'फोटो काढा आणि वापरा',
    pdp_guide_title: 'मुख्य प्रदर्शन पॅनेल (PDP) मार्गदर्शक',
    pdp_guide_desc: 'एमआरपी, निव्वळ प्रमाण, बॅच आणि निर्मिती तारीख बॉक्समध्ये संरेखित करा',
    ai_inspection_title: 'एआय पॅकेजिंग तपासणी आणि निष्कर्ष',
    ai_inspection_subtitle: 'स्वयंचलित ओसीआर निष्कर्ष आणि वैधानिक मापनशास्त्र (पॅकबंद वस्तू) नियम पडताळणी',
    new_packaging_scan: 'नवीन पॅकेजिंग स्कॅन',
    capture_upload_title: 'उत्पादन पॅकेजिंग कॅप्चर करा किंवा अपलोड करा',
    capture_upload_desc: 'पॅकेजिंग प्रतिमा (पुढे, मागे, बाजूने) अपलोड करा किंवा डिव्हाइस कॅमेरासह थेट फोटो घ्या. एआय इंजिन वैधानिक मापनशास्त्र नियमांनुसार सर्व अनिवार्य घोषणा काढते.',
    browse_photos: 'पॅकेजिंग फोटो ब्राउझ करा',
    live_field_camera: 'थेट फील्ड कॅमेरा',
    quick_catalog_testing: 'त्वरित कॅटलॉग बेंचमार्क चाचणी:',
    click_to_load_sample: 'पॅकेजिंग नमुना त्वरित लोड करण्यासाठी क्लिक करा',
    selected_samples: 'निवडलेले नमुने',
    ready_for_ocr: 'ओसीआर आणि नियम इंजिनसाठी तयार',
    save_offline_draft: 'ऑफलाइन मसुदा सेव्ह करा',
    run_ai_ocr: 'एआय ओसीआर निष्कर्ष आणि नियम मूल्यांकन चालवा',
    scanning_extracting: 'घोषणा स्कॅन आणि काढल्या जात आहेत...',
    running_ocr_engine: 'EasyOCR, कॉन्ट्रास्ट एन्हांसमेंट आणि वैधानिक मापनशास्त्र नियम इंजिन चालू आहे...',
    mandatory_declarations_check: 'अनिवार्य घोषणा तपासणी',
    lm_rules_desc: 'वैधानिक मापनशास्त्र (पॅकबंद वस्तू) नियम, 2011 नुसार, प्रत्येक किरकोळ पॅकेजवर प्रदर्शित करणे आवश्यक आहे:',
    rule_6_1_a_desc: 'नियम 6(1)(a): पिन सह उत्पादकाचे नाव आणि पोस्टल पत्ता',
    rule_6_1_b_desc: 'नियम 6(1)(b): जेनेरिक / सामान्य वस्तूचे नाव',
    rule_6_1_c_desc: 'नियम 6(1)(c): मेट्रिक एसआय युनिट्समध्ये निव्वळ प्रमाण (नियम 12)',
    rule_6_1_e_desc: 'नियम 6(1)(e): रुपये (₹) चिन्ह आणि "सर्व करांसह" एमआरपी',
    rule_6_1_d_desc: 'नियम 6(1)(d): निर्मिती/पॅकिंगचा महिना आणि वर्ष',
    rule_6_2_desc: 'नियम 6(2): ग्राहक तक्रार संपर्क (फोन/ईमेल)',
    rule_18_2_desc: 'नियम 18(2): दुहेरी किंमत किंवा रीस्टिकरिंग नाही',
    sec_25_offline_title: 'कलम 25 ऑफलाइन तपासणी',
    sec_25_offline_desc: 'क्षेत्रीय अधिकारी इंटरनेटशिवाय ऑफलाइन बाजारपेठांमध्ये पॅकेजिंग फोटो घेऊ शकतात. मसुदे स्थानिक पातळीवर रांगेत ठेवले जातात आणि कनेक्ट झाल्यावर बॅच मोडमध्ये समक्रमित केले जातात.',
    fully_compliant: 'पूर्णपणे अनुपालित',
    review_advised: 'पुनरावलोकनाचा सल्ला दिला',
    non_compliant_violations: 'गैर-अनुपालित / उल्लंघने',
    score_label: 'स्कोअर',
    manufacturer_label: 'उत्पादक:',
    category_label: 'प्रवर्ग:',
    readability_label: 'वाचनयोग्यता',
    rule_7_font_label: 'नियम 7 फॉन्ट',
    ocr_accuracy_label: 'ओसीआर अचूकता',
    inspection_complete_title: 'तपासणी पूर्ण — अधिकृत अहवाल तयार करा',
    create_certificate_desc: 'वैधानिक मापनशास्त्र कायदा 2009 च्या कलम 24 अंतर्गत वैधानिक अनुपालन प्रमाणपत्र किंवा दंडाची नोटीस तयार करा',
    print_certificate: 'प्रमाणपत्र मुद्रित करा',
    generate_report: 'अहवाल तयार करा',
    generating_report: 'अहवाल तयार होत आहे...',
    extracted_declarations_tab: 'काढलेल्या घोषणांचे पुनरावलोकन',
    lm_rules_tab: 'वैधानिक मापनशास्त्र नियम',
    ocr_evidence_tab: 'पॅकेजिंग ओसीआर पुरावे',
    re_evaluate_rules: 'नियमांचे पुनर्मूल्यांकन करा',
    inspected_sample_title: 'तपासलेला पॅकेजिंग नमुना',
    image_processed_desc: 'डेस्क्यूइंग आणि कॉन्ट्रास्ट वाढीसह प्रक्रिया केलेली प्रतिमा',
    mandatory_decl_hitl_title: 'अनिवार्य घोषणा (ह्युमन-इन-द-लूप)',
    inspect_edit_confirm_desc: 'कायदेशीर कारवाईपूर्वी ओसीआर-काढलेल्या मूल्यांची तपासणी, संपादन किंवा पुष्टी करा',
    confirmed_label: 'पुष्टी केली',
    mandatory_declaration_col: 'अनिवार्य घोषणा',
    extracted_value_col: 'काढलेले मजकूर मूल्य',
    confidence_col: 'खात्री',
    confirm_col: 'पुष्टी करा',
    missing_not_detected_placeholder: 'गहाळ किंवा सापडले नाही (प्रविष्ट करण्यासाठी क्लिक करा)',
    location_label: 'स्थान:',
    lm_eval_title: 'वैधानिक मापनशास्त्र अनुपालन मूल्यांकन',
    lm_eval_desc: 'LM(PC) नियम 2011 आणि वैधानिक मापनशास्त्र कायदा 2009 अंतर्गत स्वयंचलित नियम पडताळणी',
    passed_label: 'उत्तीर्ण',
    officer_override_pass: 'अधिकारी ओव्हरराइड (उत्तीर्ण)',
    revert_override: 'ओव्हरराइड परत करा',
    officer_override: 'अधिकारी ओव्हरराइड',
    severity_label: 'तीव्रता',
    officer_observations_title: 'अधिकारी निरीक्षणे आणि वैधानिक अंमलबजावणी शेरे',
    officer_observations_placeholder: 'कलम 49 अंतर्गत भौतिक नमुना, सील अखंडता, किरकोळ स्टोअरचे स्थान किंवा तडजोड शिफारसीसंबंधी अधिकृत निरीक्षणे प्रविष्ट करा...',
    save_signed_evidence: 'स्वाक्षरी केलेले पुरावे सेव्ह करा',
    generate_official_certificate_btn: 'अधिकृत अनुपालन प्रमाणपत्र / नोटीस तयार करा →',
    generating_btn: 'तयार होत आहे...',
    raw_ocr_text_title: 'ओसीआर इंजिनद्वारे सापडलेला कच्चा पॅकेजिंग मजकूर',
    lines_extracted: 'ओळी काढल्या',

    // LANDING PAGE (Hero & Nav)
    ministry_consumer_affairs: 'ग्राहक व्यवहार, अन्न आणि सार्वजनिक वितरण मंत्रालय',
    govt_of_india: 'भारत सरकार',
    portal_title: 'पॅकेज्ड कमोडिटीज अनुपालन पोर्टल',
    portal_tagline: 'पारदर्शक वजन. विश्वासू ग्राहक. मजबूत भारत.',
    nav_home: 'मुख्यपृष्ठ',
    nav_check_product: 'उत्पादन तपासा',
    nav_know_rules: 'नियम जाणून घ्या',
    nav_consumer_awareness: 'ग्राहक जागरूकता',
    nav_report_violation: 'उल्लंघनाची नोंद करा',
    nav_dashboard: 'डॅशबोर्ड',
    nav_resources: 'संसाधने',
    nav_about_us: 'आमच्याबद्दल',
    search_placeholder: 'उत्पादने, नियम इ. शोधा',
    right_info: 'योग्य माहिती',
    stronger_consumers: 'मजबूत ग्राहक',
    ensuring_fair_trade: 'निष्पक्ष व्यापार सुनिश्चित करणे',
    check_compliance_title: 'पॅकेज्ड कमोडिटीजचे अनुपालन तपासा',
    check_compliance_desc: 'एखादे पॅकेज केलेले उत्पादन लीगल मेट्रोलॉजी (पॅकेज्ड कमोडिटीज) नियम, २०११ चे पालन करत आहे का ते तपासा.',
    btn_check_product: 'उत्पादन तपासा',
    btn_learn_more: 'अधिक जाणून घ्या',
    badge_consumer_protection: 'ग्राहक संरक्षण',
    badge_fair_measurement: 'योग्य मोजमाप',
    badge_trusted_marketplace: 'विश्वासार्ह बाजारपेठ',
    card_check_product_desc: 'अनुपालन तपासण्यासाठी तपशील स्कॅन करा किंवा प्रविष्ट करा',
    card_understand_rules: 'नियम समजून घ्या',
    card_understand_rules_desc: 'लीगल मेट्रोलॉजी नियम, २०११ बद्दल जाणून घ्या',
    card_report_violation: 'उल्लंघनाची नोंद करा',
    card_report_violation_desc: 'निष्पक्ष व्यापार सुनिश्चित करण्यात आम्हाला मदत करा',
    card_consumer_awareness: 'ग्राहक जागरूकता',
    card_consumer_awareness_desc: 'टिपा, मार्गदर्शक आणि संसाधने',
    card_compliance_dashboard: 'अनुपालन डॅशबोर्ड',
    card_compliance_dashboard_desc: 'राज्यनिहाय अंतर्दृष्टी आणि अहवाल',

    section_check_product: 'पॅकेज केलेल्या उत्पादनाची तपासणी करा',
    lm_rules_badge: 'LM नियम २०११',
    tab_scan_barcode: 'बारकोड स्कॅन करा',
    tab_enter_details: 'तपशील प्रविष्ट करा',
    tab_upload_image: 'प्रतिमा अपलोड करा',
    scan_barcode_desc: 'उत्पादन तपशील मिळवण्यासाठी आणि अनुपालन तपासण्यासाठी पॅकेजवरील बारकोड स्कॅन करा.',
    btn_start_camera: 'कॅमेरा स्कॅनर सुरू करा',
    test_known_barcode_label: 'किंवा ज्ञात बारकोडसह चाचणी करा:',
    verify_btn: 'पडताळणी करा',
    checking_btn: 'तपासत आहे...',
    quick_demo_label: 'क्विक डेमो:',
    sample_violation_btn: 'नमुना उल्लंघन',
    enter_details_manual_link: "बारकोड नाही? तपशील स्वहस्ते प्रविष्ट करा →",
    section_categories: 'समर्थित उत्पादन श्रेणी',
    cat_food: 'अन्न आणि पेये',
    cat_cosmetics: 'वैयक्तिक काळजी आणि सौंदर्य प्रसाधने',
    cat_household: 'घरगुती उत्पादने',
    cat_healthcare: 'आरोग्य सेवा आणि ओटीसी उत्पादने',
    cat_other: 'इतर सर्व पॅकेज्ड वस्तू',
    mandatory_decl_req: 'अनिवार्य घोषणा आवश्यक:',
    mandatory_decl_list: 'उत्पादक/पॅकरचे नाव आणि पत्ता, सामान्य किंवा जेनेरिक नाव, निव्वळ प्रमाण, उत्पादनाचे/आयातीचे महिना आणि वर्ष, किरकोळ विक्री किंमत (MRP) आणि ग्राहक काळजी तपशील.',
    section_alerts: 'नवीनतम अद्यतने आणि सूचना',
    view_all_link: 'सर्व पहा',
    alert1_title: 'योग्य निव्वळ प्रमाण घोषणेवर सल्ला',
    alert1_desc: 'LM नियम, २०११ नुसार निव्वळ प्रमाण विहित युनिट्समध्ये घोषित केले आहे याची खात्री करा.',
    alert2_title: 'मल्टीपॅक वस्तूंसाठी सुधारित मार्गदर्शक तत्त्वे',
    alert2_desc: 'मल्टीपॅक पॅकेजेसवर घोषणा करण्यासाठी नवीन मार्गदर्शक तत्त्वे जारी करण्यात आली आहेत.',
    alert3_title: 'जागरूकता मोहीम: खरेदी करण्यापूर्वी तपासा',
    alert3_desc: 'माहितीपूर्ण आणि सुरक्षित ग्राहक निवडींना प्रोत्साहन देण्यासाठी आमच्या मोहिमेत सामील व्हा.',

    rules_modal_title: 'वैध मापन शास्त्र (पॅकेज केलेल्या वस्तू) नियम, २०११',
    rules_modal_subtitle: 'वैधानिक तरतुदी आणि मानके',
    rule_6_title: 'नियम ६: अनिवार्य घोषणा',
    rule_6_desc: 'प्रत्येक पॅकेजवर खालील स्पष्ट घोषणा असणे आवश्यक आहे:',
    rule_6_l1: 'उत्पादक, पॅकर किंवा आयातदाराचे नाव आणि संपूर्ण पत्ता.',
    rule_6_l2: 'पॅकेजमध्ये समाविष्ट असलेल्या वस्तूचे सामान्य किंवा जेनेरिक नाव.',
    rule_6_l3: 'वजन किंवा मापाच्या मानक एककानुसार निव्वळ प्रमाण (ग्रॅम, किलो, मिली, लिटर, मीटर).',
    rule_6_l4: 'वस्तू ज्या महिन्यात आणि वर्षात उत्पादित, पॅक किंवा आयात केली गेली.',
    rule_6_l5: 'सर्व करांसह भारतीय चलनात किरकोळ विक्री किंमत (MRP).',
    rule_6_l6: 'ग्राहक तक्रारींसाठी व्यक्ती किंवा कार्यालयाचे नाव, पत्ता, टेलिफोन नंबर आणि ईमेल.',
    rule_18_title: 'नियम १८(२): दुहेरी MRP वर बंदी',
    rule_18_desc: 'कोणताही उत्पादक, पॅकर, आयातदार किंवा विक्रेता पॅकेजवर घोषित केलेल्या किरकोळ विक्री किमतीमध्ये बदल करणार नाही, ती पुसट करणार नाही किंवा त्यावर दुसरी किंमत चिकटवणार नाही. MRP पेक्षा जास्त शुल्क आकारणे किंवा वेगवेगळ्या ठिकाणी (उदा. विमानतळ विरुद्ध स्थानिक बाजारपेठ) समान उत्पादनांसाठी दोन भिन्न MRP ठेवणे हा कायद्याच्या कलम ३६ अंतर्गत गुन्हा आहे.',
    second_schedule_title: 'दुसरे वेळापत्रक: मानक पॅकेज आकार',
    second_schedule_desc: 'फसव्या पॅकेजिंगला प्रतिबंध करण्यासाठी बेबी मिल्क, बिस्किटे, चहा, मीठ आणि खाद्यतेल यांसारख्या विशिष्ट वस्तू केवळ विहित मानक प्रमाणात (उदा. 100g, 200g, 500g, 1kg) पॅक केल्या पाहिजेत.',
    close_guidelines_btn: 'मार्गदर्शक तत्त्वे बंद करा',

    awareness_modal_title: 'जागो ग्राहक जागो — ग्राहक अधिकार',
    awareness_modal_subtitle: 'पैसे देण्यापूर्वी काय तपासायचे ते जाणून घ्या',
    awareness_point1_title: 'MRP पेक्षा जास्त पैसे कधीही देऊ नका:',
    awareness_point1_desc: "MRP वैधानिक आहे आणि त्यात नेहमी सर्व लागू करांचा (GST) समावेश असतो. पॅकबंद वस्तूंवर अतिरिक्त 'कूलिंग चार्जेस' किंवा 'सुविधा शुल्क' बेकायदेशीर आहेत.",
    awareness_point2_title: 'निव्वळ वजनाची तपासणी करा:',
    awareness_point2_desc: 'पॅकेजमध्ये अचूक घोषित वजन असल्याची खात्री करा आणि ते कमी वजनाचे नाही. रिटेल काउंटरवर उपलब्ध पडताळलेले ट्रेड स्केल वापरा.',
    awareness_point3_title: 'ग्राहक सेवा तपशील तपासा:',
    awareness_point3_desc: 'तक्रारींसाठी प्रत्येक कायदेशीर पॅकेजवर ईमेल, टेलिफोन आणि टपाल पत्ता असणे आवश्यक आहे.',
    awareness_help_title: 'तातडीची मदत हवी आहे?',
    awareness_help_text1: 'राष्ट्रीय ग्राहक हेल्पलाइनला',
    awareness_help_text2: "वर कॉल करा किंवा 8800001915 वर 'CONSUMER' एसएमएस करा.",
    understood_btn: 'समजले',

    // Dashboard Page
    products_cataloged: 'सूचीबद्ध उत्पादने',

    // Dashboard Layout

    // ECommerce Page Tabs
    select_online_marketplace_title: '2. ऑनलाइन मार्केटप्लेस लिस्टिंग निवडा',
    presets_catalog_tab: 'प्रीसेट कॅटलॉग',
    product_link_url_tab: 'उत्पादन लिंक / URL',
    select_catalog_hint: 'स्वयंचलित क्रॉस-व्हॅलिडेशनसाठी कॅटलॉग लिस्टिंग निवडा किंवा थेट उत्पादन वेब URL पेस्ट करा:',
    target_marketplace_listing: 'लक्ष्य मार्केटप्लेस लिस्टिंग',
    select_online_product: '-- ऑनलाइन उत्पादन लिस्टिंग निवडा --',
    scrape_and_fetch: 'डेटा काढा (स्क्रॅप आणि फेच)',
    quick_test_scenarios: '⚡ त्वरित चाचणी परिस्थिती (१-क्लिक भरा):',
    test_1_full_match: '✓ चाचणी १: पूर्ण जुळणी (Parle-G)',
    test_2_mrp_discrepancy: '⚠ चाचणी २: एमआरपी तफावत (ABC Drink)',
    test_3_qty_mismatch: '⚠ चाचणी ३: प्रमाण तफावत (ABC Biscuits)',
    test_6_low_confidence: '⚠ चाचणी ६: कमी आत्मविश्वास (XYZ Shampoo)',

    // Analytics Page
    analytics_title: 'जोखीम प्राधान्य आणि निर्माता विश्लेषण',
    analytics_subtitle: 'कलम ३६ अंतर्गत डेटा-आधारित निर्माता जोखीम बुद्धिमत्ता, वारंवार गुन्हे करणाऱ्यांना लक्ष्य करण्यासाठी आणि क्षेत्रीय अंमलबजावणी ऑडिटला प्राधान्य देण्यासाठी.',
    schedule_priority_audit: 'प्राधान्य ऑडिट शेड्यूल करा',
    critical_risk: 'गंभीर जोखीम',
    immediate_seizure: 'तात्काळ जप्ती / न्यायालय',
    high_risk: 'उच्च जोखीम',
    repeat_offender_multiplier: 'वारंवार गुन्हेगार गुणक',
    medium_risk: 'मध्यम जोखीम',
    scheduled_audit_watchlist: 'नियोजित ऑडिट वॉचलिस्ट',
    low_risk_compliant: 'कमी जोखीम / अनुपालन',
    clean_statutory_standing: 'स्वच्छ वैधानिक स्थिती',
    search_manufacturer: 'नाव किंवा ब्रँडद्वारे निर्माता शोधा...',
    sec_36_enforcement_index: 'कलम ३६ अंमलबजावणी आणि वारंवार गुन्हेगार निर्देशांक',
    fine_tiers: 'दंड स्तर: ₹25k / ₹50k / ₹100k + तुरुंगवास',
    manufacturer_entity: 'निर्माता संस्था',
    risk_level_header: 'जोखीम स्तर',
    inspections_header: 'तपासणी',
    repeat_violations_header: 'वारंवार उल्लंघन',
    sec_36_penalty_tier: 'कलम ३६ दंड स्तर',
    recommended_action: 'शिफारस केलेली अंमलबजावणी कारवाई',
    action_header: 'कारवाई',
    audit_commodity: 'वस्तू ऑडिट करा',

    // ECommerce Page
    ecommerce_portal_title: 'ई-कॉमर्स अंमलबजावणी पोर्टल',
    ecommerce_engine_live: 'क्रॉस-व्हॅलिडेशन इंजिन',
    ecommerce_subtitle: 'मार्केटप्लेस लिस्टिंग विरुद्ध भौतिक पॅक घोषणांची तुलना करा',
    physical_package_ocr: '1. भौतिक पॅकेज ओसीआर घोषणा',
    ecommerce_source: '2. ई-कॉमर्स मार्केटप्लेस स्रोत',
    manual_mode: 'मॅन्युअल मोड',
    scan_offline_pack: 'ऑफलाइन पॅक स्कॅन करा',
    upload_image: 'प्रतिमा अपलोड करा',
    physical_printed_mrp: 'भौतिक मुद्रित एमआरपी',
    on_pack_mrp_hint: 'पॅकवरील भौतिक वैधानिक घोषणा',
    declared_net_qty: 'पॅकवर घोषित केलेले निव्वळ प्रमाण',
    paste_ecommerce_url: 'ई-कॉमर्स उत्पादन पृष्ठ URL / लिंक पेस्ट करा',
    cross_ref_loading: 'वैधानिक घोषणा जुळवत आहे...',
    run_validation_btn: 'कायदेशीर हवामान क्रॉस-व्हॅलिडेशन चालवा',
    audit_status: 'ऑडिट स्थिती',
    recent_audits: 'अलीकडील ई-कॉमर्स क्रॉस-व्हॅलिडेशन ऑडिट',
    marketplace: 'मार्केटप्लेस',
    seller_entity: 'विक्रेता संस्था',
    listed_net_qty: 'सूचीबद्ध निव्वळ प्रमाण',
    listed_manufacturer: 'सूचीबद्ध निर्माता',
    online_declared_mrp: 'ऑनलाइन घोषित एमआरपी',
    offered_selling_price: 'ऑफर केलेली विक्री किंमत',

    // Products Page
    products_repo_title: 'नोंदणीकृत कमोडिटी भांडार',
    items_cataloged: 'कॅटलॉग केलेले आयटम',
    products_repo_subtitle: 'स्वयंचलित तफावत पडताळणीसाठी पूर्व-नोंदणीकृत पॅकेज्ड कमोडिटी मानक डेटाबेस',
    refresh_products: 'उत्पादने रिफ्रेश करा',
    register_commodity_btn: 'कमोडिटी नोंदणी करा',
    failed_load_products: 'उत्पादन भांडार लोड करण्यात अयशस्वी.',
    search_products_placeholder: 'उत्पादनाचे नाव, निर्माता, बारकोड किंवा आयडीद्वारे शोधा...',
    barcode_label: 'बारकोड',
    standard_net_qty_label: 'मानक निव्वळ प्रमाण',
    registered_mrp_label: 'नोंदणीकृत एमआरपी',
    commodity_id_col: 'कमोडिटी आयडी',
    product_name_col: 'उत्पादनाचे नाव',
    manufacturer_col: 'निर्माता',
    category_col: 'श्रेणी',
    register_new_commodity_title: 'नवीन पॅकेज्ड कमोडिटी नोंदणी करा',
    commodity_name_label: 'कमोडिटी / उत्पादनाचे नाव',
    commodity_name_placeholder: 'उदा. क्लासिक सॉल्टेड बटाटा चिप्स 50 ग्रॅम',
    mfg_name_address_label: 'निर्मात्याचे नाव आणि पत्ता',
    mfg_name_address_placeholder: 'उदा. एबीसी फूड्स प्रायव्हेट लिमिटेड, ओखला औद्योगिक क्षेत्र, दिल्ली',
    ean13_barcode_label: 'EAN-13 बारकोड',
    ean13_placeholder: 'उदा. 8901234567899',
    standard_metric_qty_label: 'मानक मेट्रिक निव्वळ प्रमाण',
    standard_metric_qty_placeholder: 'उदा. 50 ग्रॅम किंवा 100 मिली',
    registered_mrp_rupees_label: 'नोंदणीकृत एमआरपी (₹)',
    registered_mrp_rupees_placeholder: 'उदा. ₹20.00',
    save_commodity_btn: 'कमोडिटी सेव्ह करा',
    saving_btn: 'सेव्ह करत आहे...',
    cancel_btn: 'रद्द करा',

    // Landing Page Modals
    report_violation_modal_title: 'पॅकेजिंग उल्लंघनाची नोंद करा',
    report_violation_modal_subtitle: 'वैध मापन शास्त्र कायदा, २००९ (कलम ३६)',
    product_name_brand_label: 'उत्पादनाचे नाव आणि ब्रँड *',
    product_name_placeholder: 'उदा. मिनरल वॉटरची बाटली 1L / ब्रँड XYZ',
    retailer_platform_label: 'किरकोळ विक्रेता, मॉल, विमानतळ किंवा ई-कॉमर्स प्लॅटफॉर्म *',
    retailer_placeholder: 'उदा. मेट्रो स्टेशन किओस्क, ब्लिंकिट, सुपरमार्केट',
    violation_type_label: 'उल्लंघनाचा प्रकार',
    violation_type_opt_1: 'दुहेरी एमआरपी / जास्त दर (नियम १८)',
    violation_type_opt_2: 'अस्पष्ट / बदललेली एमआरपी',
    violation_type_opt_3: 'निव्वळ प्रमाण गहाळ',
    violation_type_opt_4: 'प्रमाणित नसलेले पॅकेजिंग वजन',
    violation_type_opt_5: 'निर्माता / आयातदाराचा पत्ता गहाळ',
    violation_type_opt_6: 'ग्राहक सेवा संपर्क तपशील नाहीत',
    city_state_label: 'शहर / राज्य',
    city_state_placeholder: 'उदा. नवी दिल्ली, महाराष्ट्र',
    brief_desc_evidence_label: 'संक्षिप्त वर्णन आणि पुरावा सारांश',
    brief_desc_placeholder: 'उल्लंघन, आकारलेली किंमत वि. छापील एमआरपी स्पष्ट करा...',
    submitting_btn: 'सबमिट करत आहे...',
    submit_enforcement_btn: 'अंमलबजावणी शाखेला सबमिट करा',
    alerts_circulars_title: 'अधिकृत सूचना आणि सल्लागार',
    circular_1_tag: 'परिपत्र #2025/LM/09',
    circular_1_title: 'योग्य निव्वळ प्रमाण घोषणेवर सल्लागार',
    circular_1_desc: 'राज्य अंमलबजावणी संचालनालयांना पॅकेज्ड खाद्यपदार्थ आणि डाळींवरील निव्वळ प्रमाण घोषणांची पडताळणी करण्यासाठी विशेष मोहीम राबवण्याचे निर्देश दिले आहेत.',
    circular_1_date: 'प्रकाशित: ५ सप्टें, २०२५',
    circular_2_tag: 'दुरुस्ती २०२५',
    circular_2_title: 'मल्टीपॅक कमोडिटीजसाठी सुधारित मार्गदर्शक तत्त्वे',
    circular_2_desc: 'स्वतंत्र विक्रीसाठी असलेल्या मल्टीपॅक्सनी एकूण पॅकेज एमआरपीसह वैयक्तिक युनिट किंमत जाहीर करणे आवश्यक आहे.',
    circular_2_date: 'प्रकाशित: २८ ऑगस्ट, २०२५',
    circular_3_tag: 'मोहीम',
    circular_3_title: 'राष्ट्रव्यापी मोहीम: खरेदी करण्यापूर्वी तपासा',
    circular_3_desc: 'पॅकेज्ड वस्तू खरेदी करण्यापूर्वी युनिट विक्री किंमत (USP) आणि अनिवार्य तपशील पडताळून पाहण्यासाठी ग्राहकांना प्रोत्साहित करणारी सार्वजनिक सूचना.',
    circular_3_date: 'प्रकाशित: १२ ऑगस्ट, २०२५',

    // Consumer Page
    citizen_verification_title: 'नागरिक पडताळणी आणि ग्राहक हक्क पोर्टल',
    public_rights_section: 'सार्वजनिक हक्क विभाग',
    consumer_empowerment_desc: 'ग्राहकांना वैधानिक घोषणा पडताळून पाहण्यासाठी, पौष्टिक निर्देशांक मोजण्यासाठी आणि कलम ३६ अंतर्गत थेट जास्त दर आकारण्याच्या उल्लंघनाची तक्रार करण्यासाठी सक्षम करणे.',
    lodge_complaint_btn: 'जास्त दर आकारल्याची तक्रार नोंदवा',
    select_verified_commodity: 'पडताळलेली वस्तू निवडा:',
    verified_packaged_commodity: 'पडताळलेली पॅकेज्ड कमोडिटी',
    mfg_label: 'निर्माता:',
    max_retail_price: 'कमाल किरकोळ किंमत',
    net_metric_quantity: 'निव्वळ मेट्रिक प्रमाण',
    statutory_price_protection: 'वैधानिक ग्राहक किंमत संरक्षण:',
    mrp_inclusive_taxes_desc: 'सर्व करांसह कमाल किरकोळ किंमत. छापील एमआरपीपेक्षा जास्त शुल्क आकारणे हा वैध मापन शास्त्र कायद्याच्या कलम ३६ अंतर्गत दंडनीय अपराध आहे.',
    verify_standard_units: 'नेहमी पडताळणी करा की मानक मेट्रिक युनिट्स (g/kg/ml) कोणत्याही संदिग्ध पात्रता नसताना छापलेले आहेत.',
    no_commodities_yet: 'अद्याप कोणत्याही वस्तू सूचीबद्ध नाहीत',
    commodities_will_appear_desc: 'वैध मापन शास्त्र अधिकाऱ्यांनी नोंदणी केलेल्या वस्तू वैधानिक ग्राहक पडताळणीसाठी येथे दिसतील. आपण अद्याप वरील बटणाचा वापर करून जास्त दर आकारण्याच्या उल्लंघनाची तक्रार नोंदवू शकता.',
    lodge_lm_complaint: 'वैध मापन शास्त्र तक्रार नोंदवा',
    complaint_registered_successfully: 'तक्रार यशस्वीरित्या नोंदवली गेली',
    acknowledgement_id_label: 'पावती आयडी:',
    forwarded_inspector_desc: 'कलम ३६ अंतर्गत त्वरित पडताळणीसाठी जिल्हा वैध मापन शास्त्र निरीक्षकाकडे पाठवले.',
    retail_store_name_label: 'किरकोळ दुकान / विक्रेत्याचे नाव आणि ठिकाण',
    printed_pack_mrp_label: 'मुद्रित पॅक एमआरपी',
    price_actually_charged_label: 'प्रत्यक्षात आकारलेली किंमत (₹)',
    complaint_nature_label: 'तक्रारीचे स्वरूप',
    nature_overcharging: 'एमआरपीपेक्षा जास्त दर (दुहेरी किंमत)',
    nature_deficient_qty: 'कमी निव्वळ प्रमाण / कमी माप',
    nature_missing_declarations: 'अनिवार्य घोषणा गहाळ',
    nature_smudged_date: 'पॅकिंगची अस्पष्ट / बदललेली तारीख',
    complainant_contact_number: 'तक्रारदाराचा संपर्क क्रमांक',
    evidence_remarks: 'पुरावा शेरा',
    submit_to_lmd_btn: 'वैध मापन शास्त्र विभागाकडे सबमिट करा',
    store_name_placeholder: 'उदा. रिटेल मार्ट, मार्केट रोड',
    charged_price_placeholder: 'उदा. 35.00',

    // Scan Page
    violations_label: 'उल्लंघन'
  }
};

export interface LanguageContextType {
  lang: LanguageCode;
  changeLanguage: (code: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({} as LanguageContextType);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLang] = useState<LanguageCode>('en');

  useEffect(() => {
    try {
      const stored = localStorage.getItem('lmd_lang') as LanguageCode;
      if (stored && (stored === 'en' || stored === 'hi' || stored === 'mr')) {
        setLang(stored);
      }
    } catch (e) {
      console.error(e);
    }
  }, []);

  const changeLanguage = (newLang: LanguageCode) => {
    setLang(newLang);
    try {
      localStorage.setItem('lmd_lang', newLang);
    } catch (e) {
      console.error(e);
    }
  };

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
